// Generated
#include "precompiled.h"
#include "editor_icons_all.h"

namespace fields_engine {
	using eii = editor_icon_info;
	const std::array<editor_icon_info, 1350> all_editor_icons = {
		eii{ ICON_ADDRESS_BOOK, "address_book", "Address book" },
		eii{ ICON_ADDRESS_CARD, "address_card", "Address card" },
		eii{ ICON_ALIGN_CENTER, "align_center", "Align center" },
		eii{ ICON_ALIGN_JUSTIFY, "align_justify", "Align justify" },
		eii{ ICON_ALIGN_LEFT, "align_left", "Align left" },
		eii{ ICON_ALIGN_RIGHT, "align_right", "Align right" },
		eii{ ICON_ANCHOR, "anchor", "Anchor" },
		eii{ ICON_ANCHOR_CIRCLE_CHECK, "anchor_circle_check", "Anchor circle check" },
		eii{ ICON_ANCHOR_CIRCLE_EXCLAMATION, "anchor_circle_exclamation", "Anchor circle exclamation" },
		eii{ ICON_ANCHOR_CIRCLE_XMARK, "anchor_circle_xmark", "Anchor circle xmark" },
		eii{ ICON_ANCHOR_LOCK, "anchor_lock", "Anchor lock" },
		eii{ ICON_ANGLE_DOWN, "angle_down", "Angle down" },
		eii{ ICON_ANGLE_LEFT, "angle_left", "Angle left" },
		eii{ ICON_ANGLE_RIGHT, "angle_right", "Angle right" },
		eii{ ICON_ANGLE_UP, "angle_up", "Angle up" },
		eii{ ICON_ANGLES_DOWN, "angles_down", "Angles down" },
		eii{ ICON_ANGLES_LEFT, "angles_left", "Angles left" },
		eii{ ICON_ANGLES_RIGHT, "angles_right", "Angles right" },
		eii{ ICON_ANGLES_UP, "angles_up", "Angles up" },
		eii{ ICON_ANKH, "ankh", "Ankh" },
		eii{ ICON_APPLE_WHOLE, "apple_whole", "Apple whole" },
		eii{ ICON_ARCHWAY, "archway", "Archway" },
		eii{ ICON_ARROW_DOWN, "arrow_down", "Arrow down" },
		eii{ ICON_ARROW_DOWN_1_9, "arrow_down_1_9", "Arrow down 1 9" },
		eii{ ICON_ARROW_DOWN_9_1, "arrow_down_9_1", "Arrow down 9 1" },
		eii{ ICON_ARROW_DOWN_A_Z, "arrow_down_a_z", "Arrow down a z" },
		eii{ ICON_ARROW_DOWN_LONG, "arrow_down_long", "Arrow down long" },
		eii{ ICON_ARROW_DOWN_SHORT_WIDE, "arrow_down_short_wide", "Arrow down short wide" },
		eii{ ICON_ARROW_DOWN_UP_ACROSS_LINE, "arrow_down_up_across_line", "Arrow down up across line" },
		eii{ ICON_ARROW_DOWN_UP_LOCK, "arrow_down_up_lock", "Arrow down up lock" },
		eii{ ICON_ARROW_DOWN_WIDE_SHORT, "arrow_down_wide_short", "Arrow down wide short" },
		eii{ ICON_ARROW_DOWN_Z_A, "arrow_down_z_a", "Arrow down z a" },
		eii{ ICON_ARROW_LEFT, "arrow_left", "Arrow left" },
		eii{ ICON_ARROW_LEFT_LONG, "arrow_left_long", "Arrow left long" },
		eii{ ICON_ARROW_POINTER, "arrow_pointer", "Arrow pointer" },
		eii{ ICON_ARROW_RIGHT, "arrow_right", "Arrow right" },
		eii{ ICON_ARROW_RIGHT_ARROW_LEFT, "arrow_right_arrow_left", "Arrow right arrow left" },
		eii{ ICON_ARROW_RIGHT_FROM_BRACKET, "arrow_right_from_bracket", "Arrow right from bracket" },
		eii{ ICON_ARROW_RIGHT_LONG, "arrow_right_long", "Arrow right long" },
		eii{ ICON_ARROW_RIGHT_TO_BRACKET, "arrow_right_to_bracket", "Arrow right to bracket" },
		eii{ ICON_ARROW_RIGHT_TO_CITY, "arrow_right_to_city", "Arrow right to city" },
		eii{ ICON_ARROW_ROTATE_LEFT, "arrow_rotate_left", "Arrow rotate left" },
		eii{ ICON_ARROW_ROTATE_RIGHT, "arrow_rotate_right", "Arrow rotate right" },
		eii{ ICON_ARROW_TREND_DOWN, "arrow_trend_down", "Arrow trend down" },
		eii{ ICON_ARROW_TREND_UP, "arrow_trend_up", "Arrow trend up" },
		eii{ ICON_ARROW_TURN_DOWN, "arrow_turn_down", "Arrow turn down" },
		eii{ ICON_ARROW_TURN_UP, "arrow_turn_up", "Arrow turn up" },
		eii{ ICON_ARROW_UP, "arrow_up", "Arrow up" },
		eii{ ICON_ARROW_UP_1_9, "arrow_up_1_9", "Arrow up 1 9" },
		eii{ ICON_ARROW_UP_9_1, "arrow_up_9_1", "Arrow up 9 1" },
		eii{ ICON_ARROW_UP_A_Z, "arrow_up_a_z", "Arrow up a z" },
		eii{ ICON_ARROW_UP_FROM_BRACKET, "arrow_up_from_bracket", "Arrow up from bracket" },
		eii{ ICON_ARROW_UP_FROM_GROUND_WATER, "arrow_up_from_ground_water", "Arrow up from ground water" },
		eii{ ICON_ARROW_UP_FROM_WATER_PUMP, "arrow_up_from_water_pump", "Arrow up from water pump" },
		eii{ ICON_ARROW_UP_LONG, "arrow_up_long", "Arrow up long" },
		eii{ ICON_ARROW_UP_RIGHT_DOTS, "arrow_up_right_dots", "Arrow up right dots" },
		eii{ ICON_ARROW_UP_RIGHT_FROM_SQUARE, "arrow_up_right_from_square", "Arrow up right from square" },
		eii{ ICON_ARROW_UP_SHORT_WIDE, "arrow_up_short_wide", "Arrow up short wide" },
		eii{ ICON_ARROW_UP_WIDE_SHORT, "arrow_up_wide_short", "Arrow up wide short" },
		eii{ ICON_ARROW_UP_Z_A, "arrow_up_z_a", "Arrow up z a" },
		eii{ ICON_ARROWS_DOWN_TO_LINE, "arrows_down_to_line", "Arrows down to line" },
		eii{ ICON_ARROWS_DOWN_TO_PEOPLE, "arrows_down_to_people", "Arrows down to people" },
		eii{ ICON_ARROWS_LEFT_RIGHT, "arrows_left_right", "Arrows left right" },
		eii{ ICON_ARROWS_LEFT_RIGHT_TO_LINE, "arrows_left_right_to_line", "Arrows left right to line" },
		eii{ ICON_ARROWS_ROTATE, "arrows_rotate", "Arrows rotate" },
		eii{ ICON_ARROWS_SPIN, "arrows_spin", "Arrows spin" },
		eii{ ICON_ARROWS_SPLIT_UP_AND_LEFT, "arrows_split_up_and_left", "Arrows split up and left" },
		eii{ ICON_ARROWS_TO_CIRCLE, "arrows_to_circle", "Arrows to circle" },
		eii{ ICON_ARROWS_TO_DOT, "arrows_to_dot", "Arrows to dot" },
		eii{ ICON_ARROWS_TO_EYE, "arrows_to_eye", "Arrows to eye" },
		eii{ ICON_ARROWS_TURN_RIGHT, "arrows_turn_right", "Arrows turn right" },
		eii{ ICON_ARROWS_TURN_TO_DOTS, "arrows_turn_to_dots", "Arrows turn to dots" },
		eii{ ICON_ARROWS_UP_DOWN, "arrows_up_down", "Arrows up down" },
		eii{ ICON_ARROWS_UP_DOWN_LEFT_RIGHT, "arrows_up_down_left_right", "Arrows up down left right" },
		eii{ ICON_ARROWS_UP_TO_LINE, "arrows_up_to_line", "Arrows up to line" },
		eii{ ICON_ASTERISK, "asterisk", "Asterisk" },
		eii{ ICON_ATOM, "atom", "Atom" },
		eii{ ICON_AUDIO_DESCRIPTION, "audio_description", "Audio description" },
		eii{ ICON_AUSTRAL_SIGN, "austral_sign", "Austral sign" },
		eii{ ICON_AWARD, "award", "Award" },
		eii{ ICON_BABY, "baby", "Baby" },
		eii{ ICON_BABY_CARRIAGE, "baby_carriage", "Baby carriage" },
		eii{ ICON_BACKWARD, "backward", "Backward" },
		eii{ ICON_BACKWARD_FAST, "backward_fast", "Backward fast" },
		eii{ ICON_BACKWARD_STEP, "backward_step", "Backward step" },
		eii{ ICON_BACON, "bacon", "Bacon" },
		eii{ ICON_BACTERIA, "bacteria", "Bacteria" },
		eii{ ICON_BACTERIUM, "bacterium", "Bacterium" },
		eii{ ICON_BAG_SHOPPING, "bag_shopping", "Bag shopping" },
		eii{ ICON_BAHAI, "bahai", "Bahai" },
		eii{ ICON_BAHT_SIGN, "baht_sign", "Baht sign" },
		eii{ ICON_BAN, "ban", "Ban" },
		eii{ ICON_BAN_SMOKING, "ban_smoking", "Ban smoking" },
		eii{ ICON_BANDAGE, "bandage", "Bandage" },
		eii{ ICON_BANGLADESHI_TAKA_SIGN, "bangladeshi_taka_sign", "Bangladeshi taka sign" },
		eii{ ICON_BARCODE, "barcode", "Barcode" },
		eii{ ICON_BARS, "bars", "Bars" },
		eii{ ICON_BARS_PROGRESS, "bars_progress", "Bars progress" },
		eii{ ICON_BARS_STAGGERED, "bars_staggered", "Bars staggered" },
		eii{ ICON_BASEBALL, "baseball", "Baseball" },
		eii{ ICON_BASEBALL_BAT_BALL, "baseball_bat_ball", "Baseball bat ball" },
		eii{ ICON_BASKET_SHOPPING, "basket_shopping", "Basket shopping" },
		eii{ ICON_BASKETBALL, "basketball", "Basketball" },
		eii{ ICON_BATH, "bath", "Bath" },
		eii{ ICON_BATTERY_EMPTY, "battery_empty", "Battery empty" },
		eii{ ICON_BATTERY_FULL, "battery_full", "Battery full" },
		eii{ ICON_BATTERY_HALF, "battery_half", "Battery half" },
		eii{ ICON_BATTERY_QUARTER, "battery_quarter", "Battery quarter" },
		eii{ ICON_BATTERY_THREE_QUARTERS, "battery_three_quarters", "Battery three quarters" },
		eii{ ICON_BED, "bed", "Bed" },
		eii{ ICON_BED_PULSE, "bed_pulse", "Bed pulse" },
		eii{ ICON_BEER_MUG_EMPTY, "beer_mug_empty", "Beer mug empty" },
		eii{ ICON_BELL, "bell", "Bell" },
		eii{ ICON_BELL_CONCIERGE, "bell_concierge", "Bell concierge" },
		eii{ ICON_BELL_SLASH, "bell_slash", "Bell slash" },
		eii{ ICON_BEZIER_CURVE, "bezier_curve", "Bezier curve" },
		eii{ ICON_BICYCLE, "bicycle", "Bicycle" },
		eii{ ICON_BINOCULARS, "binoculars", "Binoculars" },
		eii{ ICON_BIOHAZARD, "biohazard", "Biohazard" },
		eii{ ICON_BITCOIN_SIGN, "bitcoin_sign", "Bitcoin sign" },
		eii{ ICON_BLENDER, "blender", "Blender" },
		eii{ ICON_BLENDER_PHONE, "blender_phone", "Blender phone" },
		eii{ ICON_BLOG, "blog", "Blog" },
		eii{ ICON_BOLD, "bold", "Bold" },
		eii{ ICON_BOLT, "bolt", "Bolt" },
		eii{ ICON_BOLT_LIGHTNING, "bolt_lightning", "Bolt lightning" },
		eii{ ICON_BOMB, "bomb", "Bomb" },
		eii{ ICON_BONE, "bone", "Bone" },
		eii{ ICON_BONG, "bong", "Bong" },
		eii{ ICON_BOOK, "book", "Book" },
		eii{ ICON_BOOK_ATLAS, "book_atlas", "Book atlas" },
		eii{ ICON_BOOK_BIBLE, "book_bible", "Book bible" },
		eii{ ICON_BOOK_BOOKMARK, "book_bookmark", "Book bookmark" },
		eii{ ICON_BOOK_JOURNAL_WHILLS, "book_journal_whills", "Book journal whills" },
		eii{ ICON_BOOK_MEDICAL, "book_medical", "Book medical" },
		eii{ ICON_BOOK_OPEN, "book_open", "Book open" },
		eii{ ICON_BOOK_OPEN_READER, "book_open_reader", "Book open reader" },
		eii{ ICON_BOOK_QURAN, "book_quran", "Book quran" },
		eii{ ICON_BOOK_SKULL, "book_skull", "Book skull" },
		eii{ ICON_BOOK_TANAKH, "book_tanakh", "Book tanakh" },
		eii{ ICON_BOOKMARK, "bookmark", "Bookmark" },
		eii{ ICON_BORDER_ALL, "border_all", "Border all" },
		eii{ ICON_BORDER_NONE, "border_none", "Border none" },
		eii{ ICON_BORDER_TOP_LEFT, "border_top_left", "Border top left" },
		eii{ ICON_BORE_HOLE, "bore_hole", "Bore hole" },
		eii{ ICON_BOTTLE_DROPLET, "bottle_droplet", "Bottle droplet" },
		eii{ ICON_BOTTLE_WATER, "bottle_water", "Bottle water" },
		eii{ ICON_BOWL_FOOD, "bowl_food", "Bowl food" },
		eii{ ICON_BOWL_RICE, "bowl_rice", "Bowl rice" },
		eii{ ICON_BOWLING_BALL, "bowling_ball", "Bowling ball" },
		eii{ ICON_BOX, "box", "Box" },
		eii{ ICON_BOX_ARCHIVE, "box_archive", "Box archive" },
		eii{ ICON_BOX_OPEN, "box_open", "Box open" },
		eii{ ICON_BOX_TISSUE, "box_tissue", "Box tissue" },
		eii{ ICON_BOXES_PACKING, "boxes_packing", "Boxes packing" },
		eii{ ICON_BOXES_STACKED, "boxes_stacked", "Boxes stacked" },
		eii{ ICON_BRAILLE, "braille", "Braille" },
		eii{ ICON_BRAIN, "brain", "Brain" },
		eii{ ICON_BRAZILIAN_REAL_SIGN, "brazilian_real_sign", "Brazilian real sign" },
		eii{ ICON_BREAD_SLICE, "bread_slice", "Bread slice" },
		eii{ ICON_BRIDGE, "bridge", "Bridge" },
		eii{ ICON_BRIDGE_CIRCLE_CHECK, "bridge_circle_check", "Bridge circle check" },
		eii{ ICON_BRIDGE_CIRCLE_EXCLAMATION, "bridge_circle_exclamation", "Bridge circle exclamation" },
		eii{ ICON_BRIDGE_CIRCLE_XMARK, "bridge_circle_xmark", "Bridge circle xmark" },
		eii{ ICON_BRIDGE_LOCK, "bridge_lock", "Bridge lock" },
		eii{ ICON_BRIDGE_WATER, "bridge_water", "Bridge water" },
		eii{ ICON_BRIEFCASE, "briefcase", "Briefcase" },
		eii{ ICON_BRIEFCASE_MEDICAL, "briefcase_medical", "Briefcase medical" },
		eii{ ICON_BROOM, "broom", "Broom" },
		eii{ ICON_BROOM_BALL, "broom_ball", "Broom ball" },
		eii{ ICON_BRUSH, "brush", "Brush" },
		eii{ ICON_BUCKET, "bucket", "Bucket" },
		eii{ ICON_BUG, "bug", "Bug" },
		eii{ ICON_BUG_SLASH, "bug_slash", "Bug slash" },
		eii{ ICON_BUGS, "bugs", "Bugs" },
		eii{ ICON_BUILDING, "building", "Building" },
		eii{ ICON_BUILDING_CIRCLE_ARROW_RIGHT, "building_circle_arrow_right", "Building circle arrow right" },
		eii{ ICON_BUILDING_CIRCLE_CHECK, "building_circle_check", "Building circle check" },
		eii{ ICON_BUILDING_CIRCLE_EXCLAMATION, "building_circle_exclamation", "Building circle exclamation" },
		eii{ ICON_BUILDING_CIRCLE_XMARK, "building_circle_xmark", "Building circle xmark" },
		eii{ ICON_BUILDING_COLUMNS, "building_columns", "Building columns" },
		eii{ ICON_BUILDING_FLAG, "building_flag", "Building flag" },
		eii{ ICON_BUILDING_LOCK, "building_lock", "Building lock" },
		eii{ ICON_BUILDING_NGO, "building_ngo", "Building ngo" },
		eii{ ICON_BUILDING_SHIELD, "building_shield", "Building shield" },
		eii{ ICON_BUILDING_UN, "building_un", "Building un" },
		eii{ ICON_BUILDING_USER, "building_user", "Building user" },
		eii{ ICON_BUILDING_WHEAT, "building_wheat", "Building wheat" },
		eii{ ICON_BULLHORN, "bullhorn", "Bullhorn" },
		eii{ ICON_BULLSEYE, "bullseye", "Bullseye" },
		eii{ ICON_BURGER, "burger", "Burger" },
		eii{ ICON_BURST, "burst", "Burst" },
		eii{ ICON_BUS, "bus", "Bus" },
		eii{ ICON_BUS_SIMPLE, "bus_simple", "Bus simple" },
		eii{ ICON_BUSINESS_TIME, "business_time", "Business time" },
		eii{ ICON_CABLE_CAR, "cable_car", "Cable car" },
		eii{ ICON_CAKE_CANDLES, "cake_candles", "Cake candles" },
		eii{ ICON_CALCULATOR, "calculator", "Calculator" },
		eii{ ICON_CALENDAR, "calendar", "Calendar" },
		eii{ ICON_CALENDAR_CHECK, "calendar_check", "Calendar check" },
		eii{ ICON_CALENDAR_DAY, "calendar_day", "Calendar day" },
		eii{ ICON_CALENDAR_DAYS, "calendar_days", "Calendar days" },
		eii{ ICON_CALENDAR_MINUS, "calendar_minus", "Calendar minus" },
		eii{ ICON_CALENDAR_PLUS, "calendar_plus", "Calendar plus" },
		eii{ ICON_CALENDAR_WEEK, "calendar_week", "Calendar week" },
		eii{ ICON_CALENDAR_XMARK, "calendar_xmark", "Calendar xmark" },
		eii{ ICON_CAMERA, "camera", "Camera" },
		eii{ ICON_CAMERA_RETRO, "camera_retro", "Camera retro" },
		eii{ ICON_CAMERA_ROTATE, "camera_rotate", "Camera rotate" },
		eii{ ICON_CAMPGROUND, "campground", "Campground" },
		eii{ ICON_CANDY_CANE, "candy_cane", "Candy cane" },
		eii{ ICON_CANNABIS, "cannabis", "Cannabis" },
		eii{ ICON_CAPSULES, "capsules", "Capsules" },
		eii{ ICON_CAR, "car", "Car" },
		eii{ ICON_CAR_BATTERY, "car_battery", "Car battery" },
		eii{ ICON_CAR_BURST, "car_burst", "Car burst" },
		eii{ ICON_CAR_ON, "car_on", "Car on" },
		eii{ ICON_CAR_REAR, "car_rear", "Car rear" },
		eii{ ICON_CAR_SIDE, "car_side", "Car side" },
		eii{ ICON_CAR_TUNNEL, "car_tunnel", "Car tunnel" },
		eii{ ICON_CARAVAN, "caravan", "Caravan" },
		eii{ ICON_CARET_DOWN, "caret_down", "Caret down" },
		eii{ ICON_CARET_LEFT, "caret_left", "Caret left" },
		eii{ ICON_CARET_RIGHT, "caret_right", "Caret right" },
		eii{ ICON_CARET_UP, "caret_up", "Caret up" },
		eii{ ICON_CARROT, "carrot", "Carrot" },
		eii{ ICON_CART_ARROW_DOWN, "cart_arrow_down", "Cart arrow down" },
		eii{ ICON_CART_FLATBED, "cart_flatbed", "Cart flatbed" },
		eii{ ICON_CART_FLATBED_SUITCASE, "cart_flatbed_suitcase", "Cart flatbed suitcase" },
		eii{ ICON_CART_PLUS, "cart_plus", "Cart plus" },
		eii{ ICON_CART_SHOPPING, "cart_shopping", "Cart shopping" },
		eii{ ICON_CASH_REGISTER, "cash_register", "Cash register" },
		eii{ ICON_CAT, "cat", "Cat" },
		eii{ ICON_CEDI_SIGN, "cedi_sign", "Cedi sign" },
		eii{ ICON_CENT_SIGN, "cent_sign", "Cent sign" },
		eii{ ICON_CERTIFICATE, "certificate", "Certificate" },
		eii{ ICON_CHAIR, "chair", "Chair" },
		eii{ ICON_CHALKBOARD, "chalkboard", "Chalkboard" },
		eii{ ICON_CHALKBOARD_USER, "chalkboard_user", "Chalkboard user" },
		eii{ ICON_CHAMPAGNE_GLASSES, "champagne_glasses", "Champagne glasses" },
		eii{ ICON_CHARGING_STATION, "charging_station", "Charging station" },
		eii{ ICON_CHART_AREA, "chart_area", "Chart area" },
		eii{ ICON_CHART_BAR, "chart_bar", "Chart bar" },
		eii{ ICON_CHART_COLUMN, "chart_column", "Chart column" },
		eii{ ICON_CHART_GANTT, "chart_gantt", "Chart gantt" },
		eii{ ICON_CHART_LINE, "chart_line", "Chart line" },
		eii{ ICON_CHART_PIE, "chart_pie", "Chart pie" },
		eii{ ICON_CHART_SIMPLE, "chart_simple", "Chart simple" },
		eii{ ICON_CHECK, "check", "Check" },
		eii{ ICON_CHECK_DOUBLE, "check_double", "Check double" },
		eii{ ICON_CHECK_TO_SLOT, "check_to_slot", "Check to slot" },
		eii{ ICON_CHEESE, "cheese", "Cheese" },
		eii{ ICON_CHESS, "chess", "Chess" },
		eii{ ICON_CHESS_BISHOP, "chess_bishop", "Chess bishop" },
		eii{ ICON_CHESS_BOARD, "chess_board", "Chess board" },
		eii{ ICON_CHESS_KING, "chess_king", "Chess king" },
		eii{ ICON_CHESS_KNIGHT, "chess_knight", "Chess knight" },
		eii{ ICON_CHESS_PAWN, "chess_pawn", "Chess pawn" },
		eii{ ICON_CHESS_QUEEN, "chess_queen", "Chess queen" },
		eii{ ICON_CHESS_ROOK, "chess_rook", "Chess rook" },
		eii{ ICON_CHEVRON_DOWN, "chevron_down", "Chevron down" },
		eii{ ICON_CHEVRON_LEFT, "chevron_left", "Chevron left" },
		eii{ ICON_CHEVRON_RIGHT, "chevron_right", "Chevron right" },
		eii{ ICON_CHEVRON_UP, "chevron_up", "Chevron up" },
		eii{ ICON_CHILD, "child", "Child" },
		eii{ ICON_CHILD_COMBATANT, "child_combatant", "Child combatant" },
		eii{ ICON_CHILD_DRESS, "child_dress", "Child dress" },
		eii{ ICON_CHILD_REACHING, "child_reaching", "Child reaching" },
		eii{ ICON_CHILDREN, "children", "Children" },
		eii{ ICON_CHURCH, "church", "Church" },
		eii{ ICON_CIRCLE, "circle", "Circle" },
		eii{ ICON_CIRCLE_ARROW_DOWN, "circle_arrow_down", "Circle arrow down" },
		eii{ ICON_CIRCLE_ARROW_LEFT, "circle_arrow_left", "Circle arrow left" },
		eii{ ICON_CIRCLE_ARROW_RIGHT, "circle_arrow_right", "Circle arrow right" },
		eii{ ICON_CIRCLE_ARROW_UP, "circle_arrow_up", "Circle arrow up" },
		eii{ ICON_CIRCLE_CHECK, "circle_check", "Circle check" },
		eii{ ICON_CIRCLE_CHEVRON_DOWN, "circle_chevron_down", "Circle chevron down" },
		eii{ ICON_CIRCLE_CHEVRON_LEFT, "circle_chevron_left", "Circle chevron left" },
		eii{ ICON_CIRCLE_CHEVRON_RIGHT, "circle_chevron_right", "Circle chevron right" },
		eii{ ICON_CIRCLE_CHEVRON_UP, "circle_chevron_up", "Circle chevron up" },
		eii{ ICON_CIRCLE_DOLLAR_TO_SLOT, "circle_dollar_to_slot", "Circle dollar to slot" },
		eii{ ICON_CIRCLE_DOT, "circle_dot", "Circle dot" },
		eii{ ICON_CIRCLE_DOWN, "circle_down", "Circle down" },
		eii{ ICON_CIRCLE_EXCLAMATION, "circle_exclamation", "Circle exclamation" },
		eii{ ICON_CIRCLE_H, "circle_h", "Circle h" },
		eii{ ICON_CIRCLE_HALF_STROKE, "circle_half_stroke", "Circle half stroke" },
		eii{ ICON_CIRCLE_INFO, "circle_info", "Circle info" },
		eii{ ICON_CIRCLE_LEFT, "circle_left", "Circle left" },
		eii{ ICON_CIRCLE_MINUS, "circle_minus", "Circle minus" },
		eii{ ICON_CIRCLE_NODES, "circle_nodes", "Circle nodes" },
		eii{ ICON_CIRCLE_NOTCH, "circle_notch", "Circle notch" },
		eii{ ICON_CIRCLE_PAUSE, "circle_pause", "Circle pause" },
		eii{ ICON_CIRCLE_PLAY, "circle_play", "Circle play" },
		eii{ ICON_CIRCLE_PLUS, "circle_plus", "Circle plus" },
		eii{ ICON_CIRCLE_QUESTION, "circle_question", "Circle question" },
		eii{ ICON_CIRCLE_RADIATION, "circle_radiation", "Circle radiation" },
		eii{ ICON_CIRCLE_RIGHT, "circle_right", "Circle right" },
		eii{ ICON_CIRCLE_STOP, "circle_stop", "Circle stop" },
		eii{ ICON_CIRCLE_UP, "circle_up", "Circle up" },
		eii{ ICON_CIRCLE_USER, "circle_user", "Circle user" },
		eii{ ICON_CIRCLE_XMARK, "circle_xmark", "Circle xmark" },
		eii{ ICON_CITY, "city", "City" },
		eii{ ICON_CLAPPERBOARD, "clapperboard", "Clapperboard" },
		eii{ ICON_CLIPBOARD, "clipboard", "Clipboard" },
		eii{ ICON_CLIPBOARD_CHECK, "clipboard_check", "Clipboard check" },
		eii{ ICON_CLIPBOARD_LIST, "clipboard_list", "Clipboard list" },
		eii{ ICON_CLIPBOARD_QUESTION, "clipboard_question", "Clipboard question" },
		eii{ ICON_CLIPBOARD_USER, "clipboard_user", "Clipboard user" },
		eii{ ICON_CLOCK, "clock", "Clock" },
		eii{ ICON_CLOCK_ROTATE_LEFT, "clock_rotate_left", "Clock rotate left" },
		eii{ ICON_CLONE, "clone", "Clone" },
		eii{ ICON_CLOSED_CAPTIONING, "closed_captioning", "Closed captioning" },
		eii{ ICON_CLOUD, "cloud", "Cloud" },
		eii{ ICON_CLOUD_ARROW_DOWN, "cloud_arrow_down", "Cloud arrow down" },
		eii{ ICON_CLOUD_ARROW_UP, "cloud_arrow_up", "Cloud arrow up" },
		eii{ ICON_CLOUD_BOLT, "cloud_bolt", "Cloud bolt" },
		eii{ ICON_CLOUD_MEATBALL, "cloud_meatball", "Cloud meatball" },
		eii{ ICON_CLOUD_MOON, "cloud_moon", "Cloud moon" },
		eii{ ICON_CLOUD_MOON_RAIN, "cloud_moon_rain", "Cloud moon rain" },
		eii{ ICON_CLOUD_RAIN, "cloud_rain", "Cloud rain" },
		eii{ ICON_CLOUD_SHOWERS_HEAVY, "cloud_showers_heavy", "Cloud showers heavy" },
		eii{ ICON_CLOUD_SHOWERS_WATER, "cloud_showers_water", "Cloud showers water" },
		eii{ ICON_CLOUD_SUN, "cloud_sun", "Cloud sun" },
		eii{ ICON_CLOUD_SUN_RAIN, "cloud_sun_rain", "Cloud sun rain" },
		eii{ ICON_CLOVER, "clover", "Clover" },
		eii{ ICON_CODE, "code", "Code" },
		eii{ ICON_CODE_BRANCH, "code_branch", "Code branch" },
		eii{ ICON_CODE_COMMIT, "code_commit", "Code commit" },
		eii{ ICON_CODE_COMPARE, "code_compare", "Code compare" },
		eii{ ICON_CODE_FORK, "code_fork", "Code fork" },
		eii{ ICON_CODE_MERGE, "code_merge", "Code merge" },
		eii{ ICON_CODE_PULL_REQUEST, "code_pull_request", "Code pull request" },
		eii{ ICON_COINS, "coins", "Coins" },
		eii{ ICON_COLON_SIGN, "colon_sign", "Colon sign" },
		eii{ ICON_COMMENT, "comment", "Comment" },
		eii{ ICON_COMMENT_DOLLAR, "comment_dollar", "Comment dollar" },
		eii{ ICON_COMMENT_DOTS, "comment_dots", "Comment dots" },
		eii{ ICON_COMMENT_MEDICAL, "comment_medical", "Comment medical" },
		eii{ ICON_COMMENT_SLASH, "comment_slash", "Comment slash" },
		eii{ ICON_COMMENT_SMS, "comment_sms", "Comment sms" },
		eii{ ICON_COMMENTS, "comments", "Comments" },
		eii{ ICON_COMMENTS_DOLLAR, "comments_dollar", "Comments dollar" },
		eii{ ICON_COMPACT_DISC, "compact_disc", "Compact disc" },
		eii{ ICON_COMPASS, "compass", "Compass" },
		eii{ ICON_COMPASS_DRAFTING, "compass_drafting", "Compass drafting" },
		eii{ ICON_COMPRESS, "compress", "Compress" },
		eii{ ICON_COMPUTER, "computer", "Computer" },
		eii{ ICON_COMPUTER_MOUSE, "computer_mouse", "Computer mouse" },
		eii{ ICON_COOKIE, "cookie", "Cookie" },
		eii{ ICON_COOKIE_BITE, "cookie_bite", "Cookie bite" },
		eii{ ICON_COPY, "copy", "Copy" },
		eii{ ICON_COPYRIGHT, "copyright", "Copyright" },
		eii{ ICON_COUCH, "couch", "Couch" },
		eii{ ICON_COW, "cow", "Cow" },
		eii{ ICON_CREDIT_CARD, "credit_card", "Credit card" },
		eii{ ICON_CROP, "crop", "Crop" },
		eii{ ICON_CROP_SIMPLE, "crop_simple", "Crop simple" },
		eii{ ICON_CROSS, "cross", "Cross" },
		eii{ ICON_CROSSHAIRS, "crosshairs", "Crosshairs" },
		eii{ ICON_CROW, "crow", "Crow" },
		eii{ ICON_CROWN, "crown", "Crown" },
		eii{ ICON_CRUTCH, "crutch", "Crutch" },
		eii{ ICON_CRUZEIRO_SIGN, "cruzeiro_sign", "Cruzeiro sign" },
		eii{ ICON_CUBE, "cube", "Cube" },
		eii{ ICON_CUBES, "cubes", "Cubes" },
		eii{ ICON_CUBES_STACKED, "cubes_stacked", "Cubes stacked" },
		eii{ ICON_DATABASE, "database", "Database" },
		eii{ ICON_DELETE_LEFT, "delete_left", "Delete left" },
		eii{ ICON_DEMOCRAT, "democrat", "Democrat" },
		eii{ ICON_DESKTOP, "desktop", "Desktop" },
		eii{ ICON_DHARMACHAKRA, "dharmachakra", "Dharmachakra" },
		eii{ ICON_DIAGRAM_NEXT, "diagram_next", "Diagram next" },
		eii{ ICON_DIAGRAM_PREDECESSOR, "diagram_predecessor", "Diagram predecessor" },
		eii{ ICON_DIAGRAM_PROJECT, "diagram_project", "Diagram project" },
		eii{ ICON_DIAGRAM_SUCCESSOR, "diagram_successor", "Diagram successor" },
		eii{ ICON_DIAMOND, "diamond", "Diamond" },
		eii{ ICON_DIAMOND_TURN_RIGHT, "diamond_turn_right", "Diamond turn right" },
		eii{ ICON_DICE, "dice", "Dice" },
		eii{ ICON_DICE_D20, "dice_d20", "Dice d20" },
		eii{ ICON_DICE_D6, "dice_d6", "Dice d6" },
		eii{ ICON_DICE_FIVE, "dice_five", "Dice five" },
		eii{ ICON_DICE_FOUR, "dice_four", "Dice four" },
		eii{ ICON_DICE_ONE, "dice_one", "Dice one" },
		eii{ ICON_DICE_SIX, "dice_six", "Dice six" },
		eii{ ICON_DICE_THREE, "dice_three", "Dice three" },
		eii{ ICON_DICE_TWO, "dice_two", "Dice two" },
		eii{ ICON_DISEASE, "disease", "Disease" },
		eii{ ICON_DISPLAY, "display", "Display" },
		eii{ ICON_DIVIDE, "divide", "Divide" },
		eii{ ICON_DNA, "dna", "Dna" },
		eii{ ICON_DOG, "dog", "Dog" },
		eii{ ICON_DOLLAR_SIGN, "dollar_sign", "Dollar sign" },
		eii{ ICON_DOLLY, "dolly", "Dolly" },
		eii{ ICON_DONG_SIGN, "dong_sign", "Dong sign" },
		eii{ ICON_DOOR_CLOSED, "door_closed", "Door closed" },
		eii{ ICON_DOOR_OPEN, "door_open", "Door open" },
		eii{ ICON_DOVE, "dove", "Dove" },
		eii{ ICON_DOWN_LEFT_AND_UP_RIGHT_TO_CENTER, "down_left_and_up_right_to_center", "Down left and up right to center" },
		eii{ ICON_DOWN_LONG, "down_long", "Down long" },
		eii{ ICON_DOWNLOAD, "download", "Download" },
		eii{ ICON_DRAGON, "dragon", "Dragon" },
		eii{ ICON_DRAW_POLYGON, "draw_polygon", "Draw polygon" },
		eii{ ICON_DROPLET, "droplet", "Droplet" },
		eii{ ICON_DROPLET_SLASH, "droplet_slash", "Droplet slash" },
		eii{ ICON_DRUM, "drum", "Drum" },
		eii{ ICON_DRUM_STEELPAN, "drum_steelpan", "Drum steelpan" },
		eii{ ICON_DRUMSTICK_BITE, "drumstick_bite", "Drumstick bite" },
		eii{ ICON_DUMBBELL, "dumbbell", "Dumbbell" },
		eii{ ICON_DUMPSTER, "dumpster", "Dumpster" },
		eii{ ICON_DUMPSTER_FIRE, "dumpster_fire", "Dumpster fire" },
		eii{ ICON_DUNGEON, "dungeon", "Dungeon" },
		eii{ ICON_EAR_DEAF, "ear_deaf", "Ear deaf" },
		eii{ ICON_EAR_LISTEN, "ear_listen", "Ear listen" },
		eii{ ICON_EARTH_AFRICA, "earth_africa", "Earth africa" },
		eii{ ICON_EARTH_AMERICAS, "earth_americas", "Earth americas" },
		eii{ ICON_EARTH_ASIA, "earth_asia", "Earth asia" },
		eii{ ICON_EARTH_EUROPE, "earth_europe", "Earth europe" },
		eii{ ICON_EARTH_OCEANIA, "earth_oceania", "Earth oceania" },
		eii{ ICON_EGG, "egg", "Egg" },
		eii{ ICON_EJECT, "eject", "Eject" },
		eii{ ICON_ELEVATOR, "elevator", "Elevator" },
		eii{ ICON_ELLIPSIS, "ellipsis", "Ellipsis" },
		eii{ ICON_ELLIPSIS_VERTICAL, "ellipsis_vertical", "Ellipsis vertical" },
		eii{ ICON_ENVELOPE, "envelope", "Envelope" },
		eii{ ICON_ENVELOPE_CIRCLE_CHECK, "envelope_circle_check", "Envelope circle check" },
		eii{ ICON_ENVELOPE_OPEN, "envelope_open", "Envelope open" },
		eii{ ICON_ENVELOPE_OPEN_TEXT, "envelope_open_text", "Envelope open text" },
		eii{ ICON_ENVELOPES_BULK, "envelopes_bulk", "Envelopes bulk" },
		eii{ ICON_ERASER, "eraser", "Eraser" },
		eii{ ICON_ETHERNET, "ethernet", "Ethernet" },
		eii{ ICON_EURO_SIGN, "euro_sign", "Euro sign" },
		eii{ ICON_EXPAND, "expand", "Expand" },
		eii{ ICON_EXPLOSION, "explosion", "Explosion" },
		eii{ ICON_EYE, "eye", "Eye" },
		eii{ ICON_EYE_DROPPER, "eye_dropper", "Eye dropper" },
		eii{ ICON_EYE_LOW_VISION, "eye_low_vision", "Eye low vision" },
		eii{ ICON_EYE_SLASH, "eye_slash", "Eye slash" },
		eii{ ICON_F, "f", "F" },
		eii{ ICON_FACE_ANGRY, "face_angry", "Face angry" },
		eii{ ICON_FACE_DIZZY, "face_dizzy", "Face dizzy" },
		eii{ ICON_FACE_FLUSHED, "face_flushed", "Face flushed" },
		eii{ ICON_FACE_FROWN, "face_frown", "Face frown" },
		eii{ ICON_FACE_FROWN_OPEN, "face_frown_open", "Face frown open" },
		eii{ ICON_FACE_GRIMACE, "face_grimace", "Face grimace" },
		eii{ ICON_FACE_GRIN, "face_grin", "Face grin" },
		eii{ ICON_FACE_GRIN_BEAM, "face_grin_beam", "Face grin beam" },
		eii{ ICON_FACE_GRIN_BEAM_SWEAT, "face_grin_beam_sweat", "Face grin beam sweat" },
		eii{ ICON_FACE_GRIN_HEARTS, "face_grin_hearts", "Face grin hearts" },
		eii{ ICON_FACE_GRIN_SQUINT, "face_grin_squint", "Face grin squint" },
		eii{ ICON_FACE_GRIN_SQUINT_TEARS, "face_grin_squint_tears", "Face grin squint tears" },
		eii{ ICON_FACE_GRIN_STARS, "face_grin_stars", "Face grin stars" },
		eii{ ICON_FACE_GRIN_TEARS, "face_grin_tears", "Face grin tears" },
		eii{ ICON_FACE_GRIN_TONGUE, "face_grin_tongue", "Face grin tongue" },
		eii{ ICON_FACE_GRIN_TONGUE_SQUINT, "face_grin_tongue_squint", "Face grin tongue squint" },
		eii{ ICON_FACE_GRIN_TONGUE_WINK, "face_grin_tongue_wink", "Face grin tongue wink" },
		eii{ ICON_FACE_GRIN_WIDE, "face_grin_wide", "Face grin wide" },
		eii{ ICON_FACE_GRIN_WINK, "face_grin_wink", "Face grin wink" },
		eii{ ICON_FACE_KISS, "face_kiss", "Face kiss" },
		eii{ ICON_FACE_KISS_BEAM, "face_kiss_beam", "Face kiss beam" },
		eii{ ICON_FACE_KISS_WINK_HEART, "face_kiss_wink_heart", "Face kiss wink heart" },
		eii{ ICON_FACE_LAUGH, "face_laugh", "Face laugh" },
		eii{ ICON_FACE_LAUGH_BEAM, "face_laugh_beam", "Face laugh beam" },
		eii{ ICON_FACE_LAUGH_SQUINT, "face_laugh_squint", "Face laugh squint" },
		eii{ ICON_FACE_LAUGH_WINK, "face_laugh_wink", "Face laugh wink" },
		eii{ ICON_FACE_MEH, "face_meh", "Face meh" },
		eii{ ICON_FACE_MEH_BLANK, "face_meh_blank", "Face meh blank" },
		eii{ ICON_FACE_ROLLING_EYES, "face_rolling_eyes", "Face rolling eyes" },
		eii{ ICON_FACE_SAD_CRY, "face_sad_cry", "Face sad cry" },
		eii{ ICON_FACE_SAD_TEAR, "face_sad_tear", "Face sad tear" },
		eii{ ICON_FACE_SMILE, "face_smile", "Face smile" },
		eii{ ICON_FACE_SMILE_BEAM, "face_smile_beam", "Face smile beam" },
		eii{ ICON_FACE_SMILE_WINK, "face_smile_wink", "Face smile wink" },
		eii{ ICON_FACE_SURPRISE, "face_surprise", "Face surprise" },
		eii{ ICON_FACE_TIRED, "face_tired", "Face tired" },
		eii{ ICON_FAN, "fan", "Fan" },
		eii{ ICON_FAUCET, "faucet", "Faucet" },
		eii{ ICON_FAUCET_DRIP, "faucet_drip", "Faucet drip" },
		eii{ ICON_FAX, "fax", "Fax" },
		eii{ ICON_FEATHER, "feather", "Feather" },
		eii{ ICON_FEATHER_POINTED, "feather_pointed", "Feather pointed" },
		eii{ ICON_FERRY, "ferry", "Ferry" },
		eii{ ICON_FILE, "file", "File" },
		eii{ ICON_FILE_ARROW_DOWN, "file_arrow_down", "File arrow down" },
		eii{ ICON_FILE_ARROW_UP, "file_arrow_up", "File arrow up" },
		eii{ ICON_FILE_AUDIO, "file_audio", "File audio" },
		eii{ ICON_FILE_CIRCLE_CHECK, "file_circle_check", "File circle check" },
		eii{ ICON_FILE_CIRCLE_EXCLAMATION, "file_circle_exclamation", "File circle exclamation" },
		eii{ ICON_FILE_CIRCLE_MINUS, "file_circle_minus", "File circle minus" },
		eii{ ICON_FILE_CIRCLE_PLUS, "file_circle_plus", "File circle plus" },
		eii{ ICON_FILE_CIRCLE_QUESTION, "file_circle_question", "File circle question" },
		eii{ ICON_FILE_CIRCLE_XMARK, "file_circle_xmark", "File circle xmark" },
		eii{ ICON_FILE_CODE, "file_code", "File code" },
		eii{ ICON_FILE_CONTRACT, "file_contract", "File contract" },
		eii{ ICON_FILE_CSV, "file_csv", "File csv" },
		eii{ ICON_FILE_EXCEL, "file_excel", "File excel" },
		eii{ ICON_FILE_EXPORT, "file_export", "File export" },
		eii{ ICON_FILE_IMAGE, "file_image", "File image" },
		eii{ ICON_FILE_IMPORT, "file_import", "File import" },
		eii{ ICON_FILE_INVOICE, "file_invoice", "File invoice" },
		eii{ ICON_FILE_INVOICE_DOLLAR, "file_invoice_dollar", "File invoice dollar" },
		eii{ ICON_FILE_LINES, "file_lines", "File lines" },
		eii{ ICON_FILE_MEDICAL, "file_medical", "File medical" },
		eii{ ICON_FILE_PDF, "file_pdf", "File pdf" },
		eii{ ICON_FILE_PEN, "file_pen", "File pen" },
		eii{ ICON_FILE_POWERPOINT, "file_powerpoint", "File powerpoint" },
		eii{ ICON_FILE_PRESCRIPTION, "file_prescription", "File prescription" },
		eii{ ICON_FILE_SHIELD, "file_shield", "File shield" },
		eii{ ICON_FILE_SIGNATURE, "file_signature", "File signature" },
		eii{ ICON_FILE_VIDEO, "file_video", "File video" },
		eii{ ICON_FILE_WAVEFORM, "file_waveform", "File waveform" },
		eii{ ICON_FILE_WORD, "file_word", "File word" },
		eii{ ICON_FILE_ZIPPER, "file_zipper", "File zipper" },
		eii{ ICON_FILL, "fill", "Fill" },
		eii{ ICON_FILL_DRIP, "fill_drip", "Fill drip" },
		eii{ ICON_FILM, "film", "Film" },
		eii{ ICON_FILTER, "filter", "Filter" },
		eii{ ICON_FILTER_CIRCLE_DOLLAR, "filter_circle_dollar", "Filter circle dollar" },
		eii{ ICON_FILTER_CIRCLE_XMARK, "filter_circle_xmark", "Filter circle xmark" },
		eii{ ICON_FINGERPRINT, "fingerprint", "Fingerprint" },
		eii{ ICON_FIRE, "fire", "Fire" },
		eii{ ICON_FIRE_BURNER, "fire_burner", "Fire burner" },
		eii{ ICON_FIRE_EXTINGUISHER, "fire_extinguisher", "Fire extinguisher" },
		eii{ ICON_FIRE_FLAME_CURVED, "fire_flame_curved", "Fire flame curved" },
		eii{ ICON_FIRE_FLAME_SIMPLE, "fire_flame_simple", "Fire flame simple" },
		eii{ ICON_FISH, "fish", "Fish" },
		eii{ ICON_FISH_FINS, "fish_fins", "Fish fins" },
		eii{ ICON_FLAG, "flag", "Flag" },
		eii{ ICON_FLAG_CHECKERED, "flag_checkered", "Flag checkered" },
		eii{ ICON_FLAG_USA, "flag_usa", "Flag usa" },
		eii{ ICON_FLASK, "flask", "Flask" },
		eii{ ICON_FLASK_VIAL, "flask_vial", "Flask vial" },
		eii{ ICON_FLOPPY_DISK, "floppy_disk", "Floppy disk" },
		eii{ ICON_FLORIN_SIGN, "florin_sign", "Florin sign" },
		eii{ ICON_FOLDER, "folder", "Folder" },
		eii{ ICON_FOLDER_CLOSED, "folder_closed", "Folder closed" },
		eii{ ICON_FOLDER_MINUS, "folder_minus", "Folder minus" },
		eii{ ICON_FOLDER_OPEN, "folder_open", "Folder open" },
		eii{ ICON_FOLDER_PLUS, "folder_plus", "Folder plus" },
		eii{ ICON_FOLDER_TREE, "folder_tree", "Folder tree" },
		eii{ ICON_FONT, "font", "Font" },
		eii{ ICON_FONT_AWESOME, "font_awesome", "Font awesome" },
		eii{ ICON_FOOTBALL, "football", "Football" },
		eii{ ICON_FORWARD, "forward", "Forward" },
		eii{ ICON_FORWARD_FAST, "forward_fast", "Forward fast" },
		eii{ ICON_FORWARD_STEP, "forward_step", "Forward step" },
		eii{ ICON_FRANC_SIGN, "franc_sign", "Franc sign" },
		eii{ ICON_FROG, "frog", "Frog" },
		eii{ ICON_FUTBOL, "futbol", "Futbol" },
		eii{ ICON_GAMEPAD, "gamepad", "Gamepad" },
		eii{ ICON_GAS_PUMP, "gas_pump", "Gas pump" },
		eii{ ICON_GAUGE, "gauge", "Gauge" },
		eii{ ICON_GAUGE_HIGH, "gauge_high", "Gauge high" },
		eii{ ICON_GAUGE_SIMPLE, "gauge_simple", "Gauge simple" },
		eii{ ICON_GAUGE_SIMPLE_HIGH, "gauge_simple_high", "Gauge simple high" },
		eii{ ICON_GAVEL, "gavel", "Gavel" },
		eii{ ICON_GEAR, "gear", "Gear" },
		eii{ ICON_GEARS, "gears", "Gears" },
		eii{ ICON_GEM, "gem", "Gem" },
		eii{ ICON_GENDERLESS, "genderless", "Genderless" },
		eii{ ICON_GHOST, "ghost", "Ghost" },
		eii{ ICON_GIFT, "gift", "Gift" },
		eii{ ICON_GIFTS, "gifts", "Gifts" },
		eii{ ICON_GLASS_WATER, "glass_water", "Glass water" },
		eii{ ICON_GLASS_WATER_DROPLET, "glass_water_droplet", "Glass water droplet" },
		eii{ ICON_GLASSES, "glasses", "Glasses" },
		eii{ ICON_GLOBE, "globe", "Globe" },
		eii{ ICON_GOLF_BALL_TEE, "golf_ball_tee", "Golf ball tee" },
		eii{ ICON_GOPURAM, "gopuram", "Gopuram" },
		eii{ ICON_GRADUATION_CAP, "graduation_cap", "Graduation cap" },
		eii{ ICON_GREATER_THAN, "greater_than", "Greater than" },
		eii{ ICON_GREATER_THAN_EQUAL, "greater_than_equal", "Greater than equal" },
		eii{ ICON_GRIP, "grip", "Grip" },
		eii{ ICON_GRIP_LINES, "grip_lines", "Grip lines" },
		eii{ ICON_GRIP_LINES_VERTICAL, "grip_lines_vertical", "Grip lines vertical" },
		eii{ ICON_GRIP_VERTICAL, "grip_vertical", "Grip vertical" },
		eii{ ICON_GROUP_ARROWS_ROTATE, "group_arrows_rotate", "Group arrows rotate" },
		eii{ ICON_GUARANI_SIGN, "guarani_sign", "Guarani sign" },
		eii{ ICON_GUITAR, "guitar", "Guitar" },
		eii{ ICON_GUN, "gun", "Gun" },
		eii{ ICON_HAMMER, "hammer", "Hammer" },
		eii{ ICON_HAMSA, "hamsa", "Hamsa" },
		eii{ ICON_HAND, "hand", "Hand" },
		eii{ ICON_HAND_BACK_FIST, "hand_back_fist", "Hand back fist" },
		eii{ ICON_HAND_DOTS, "hand_dots", "Hand dots" },
		eii{ ICON_HAND_FIST, "hand_fist", "Hand fist" },
		eii{ ICON_HAND_HOLDING, "hand_holding", "Hand holding" },
		eii{ ICON_HAND_HOLDING_DOLLAR, "hand_holding_dollar", "Hand holding dollar" },
		eii{ ICON_HAND_HOLDING_DROPLET, "hand_holding_droplet", "Hand holding droplet" },
		eii{ ICON_HAND_HOLDING_HAND, "hand_holding_hand", "Hand holding hand" },
		eii{ ICON_HAND_HOLDING_HEART, "hand_holding_heart", "Hand holding heart" },
		eii{ ICON_HAND_HOLDING_MEDICAL, "hand_holding_medical", "Hand holding medical" },
		eii{ ICON_HAND_LIZARD, "hand_lizard", "Hand lizard" },
		eii{ ICON_HAND_MIDDLE_FINGER, "hand_middle_finger", "Hand middle finger" },
		eii{ ICON_HAND_PEACE, "hand_peace", "Hand peace" },
		eii{ ICON_HAND_POINT_DOWN, "hand_point_down", "Hand point down" },
		eii{ ICON_HAND_POINT_LEFT, "hand_point_left", "Hand point left" },
		eii{ ICON_HAND_POINT_RIGHT, "hand_point_right", "Hand point right" },
		eii{ ICON_HAND_POINT_UP, "hand_point_up", "Hand point up" },
		eii{ ICON_HAND_POINTER, "hand_pointer", "Hand pointer" },
		eii{ ICON_HAND_SCISSORS, "hand_scissors", "Hand scissors" },
		eii{ ICON_HAND_SPARKLES, "hand_sparkles", "Hand sparkles" },
		eii{ ICON_HAND_SPOCK, "hand_spock", "Hand spock" },
		eii{ ICON_HANDCUFFS, "handcuffs", "Handcuffs" },
		eii{ ICON_HANDS, "hands", "Hands" },
		eii{ ICON_HANDS_ASL_INTERPRETING, "hands_asl_interpreting", "Hands asl interpreting" },
		eii{ ICON_HANDS_BOUND, "hands_bound", "Hands bound" },
		eii{ ICON_HANDS_BUBBLES, "hands_bubbles", "Hands bubbles" },
		eii{ ICON_HANDS_CLAPPING, "hands_clapping", "Hands clapping" },
		eii{ ICON_HANDS_HOLDING, "hands_holding", "Hands holding" },
		eii{ ICON_HANDS_HOLDING_CHILD, "hands_holding_child", "Hands holding child" },
		eii{ ICON_HANDS_HOLDING_CIRCLE, "hands_holding_circle", "Hands holding circle" },
		eii{ ICON_HANDS_PRAYING, "hands_praying", "Hands praying" },
		eii{ ICON_HANDSHAKE, "handshake", "Handshake" },
		eii{ ICON_HANDSHAKE_ANGLE, "handshake_angle", "Handshake angle" },
		eii{ ICON_HANDSHAKE_SIMPLE, "handshake_simple", "Handshake simple" },
		eii{ ICON_HANDSHAKE_SIMPLE_SLASH, "handshake_simple_slash", "Handshake simple slash" },
		eii{ ICON_HANDSHAKE_SLASH, "handshake_slash", "Handshake slash" },
		eii{ ICON_HANUKIAH, "hanukiah", "Hanukiah" },
		eii{ ICON_HARD_DRIVE, "hard_drive", "Hard drive" },
		eii{ ICON_HASHTAG, "hashtag", "Hashtag" },
		eii{ ICON_HAT_COWBOY, "hat_cowboy", "Hat cowboy" },
		eii{ ICON_HAT_COWBOY_SIDE, "hat_cowboy_side", "Hat cowboy side" },
		eii{ ICON_HAT_WIZARD, "hat_wizard", "Hat wizard" },
		eii{ ICON_HEAD_SIDE_COUGH, "head_side_cough", "Head side cough" },
		eii{ ICON_HEAD_SIDE_COUGH_SLASH, "head_side_cough_slash", "Head side cough slash" },
		eii{ ICON_HEAD_SIDE_MASK, "head_side_mask", "Head side mask" },
		eii{ ICON_HEAD_SIDE_VIRUS, "head_side_virus", "Head side virus" },
		eii{ ICON_HEADING, "heading", "Heading" },
		eii{ ICON_HEADPHONES, "headphones", "Headphones" },
		eii{ ICON_HEADPHONES_SIMPLE, "headphones_simple", "Headphones simple" },
		eii{ ICON_HEADSET, "headset", "Headset" },
		eii{ ICON_HEART, "heart", "Heart" },
		eii{ ICON_HEART_CIRCLE_BOLT, "heart_circle_bolt", "Heart circle bolt" },
		eii{ ICON_HEART_CIRCLE_CHECK, "heart_circle_check", "Heart circle check" },
		eii{ ICON_HEART_CIRCLE_EXCLAMATION, "heart_circle_exclamation", "Heart circle exclamation" },
		eii{ ICON_HEART_CIRCLE_MINUS, "heart_circle_minus", "Heart circle minus" },
		eii{ ICON_HEART_CIRCLE_PLUS, "heart_circle_plus", "Heart circle plus" },
		eii{ ICON_HEART_CIRCLE_XMARK, "heart_circle_xmark", "Heart circle xmark" },
		eii{ ICON_HEART_CRACK, "heart_crack", "Heart crack" },
		eii{ ICON_HEART_PULSE, "heart_pulse", "Heart pulse" },
		eii{ ICON_HELICOPTER, "helicopter", "Helicopter" },
		eii{ ICON_HELICOPTER_SYMBOL, "helicopter_symbol", "Helicopter symbol" },
		eii{ ICON_HELMET_SAFETY, "helmet_safety", "Helmet safety" },
		eii{ ICON_HELMET_UN, "helmet_un", "Helmet un" },
		eii{ ICON_HIGHLIGHTER, "highlighter", "Highlighter" },
		eii{ ICON_HILL_AVALANCHE, "hill_avalanche", "Hill avalanche" },
		eii{ ICON_HILL_ROCKSLIDE, "hill_rockslide", "Hill rockslide" },
		eii{ ICON_HIPPO, "hippo", "Hippo" },
		eii{ ICON_HOCKEY_PUCK, "hockey_puck", "Hockey puck" },
		eii{ ICON_HOLLY_BERRY, "holly_berry", "Holly berry" },
		eii{ ICON_HORSE, "horse", "Horse" },
		eii{ ICON_HORSE_HEAD, "horse_head", "Horse head" },
		eii{ ICON_HOSPITAL, "hospital", "Hospital" },
		eii{ ICON_HOSPITAL_USER, "hospital_user", "Hospital user" },
		eii{ ICON_HOT_TUB_PERSON, "hot_tub_person", "Hot tub person" },
		eii{ ICON_HOTDOG, "hotdog", "Hotdog" },
		eii{ ICON_HOTEL, "hotel", "Hotel" },
		eii{ ICON_HOURGLASS, "hourglass", "Hourglass" },
		eii{ ICON_HOURGLASS_END, "hourglass_end", "Hourglass end" },
		eii{ ICON_HOURGLASS_HALF, "hourglass_half", "Hourglass half" },
		eii{ ICON_HOURGLASS_START, "hourglass_start", "Hourglass start" },
		eii{ ICON_HOUSE, "house", "House" },
		eii{ ICON_HOUSE_CHIMNEY, "house_chimney", "House chimney" },
		eii{ ICON_HOUSE_CHIMNEY_CRACK, "house_chimney_crack", "House chimney crack" },
		eii{ ICON_HOUSE_CHIMNEY_MEDICAL, "house_chimney_medical", "House chimney medical" },
		eii{ ICON_HOUSE_CHIMNEY_USER, "house_chimney_user", "House chimney user" },
		eii{ ICON_HOUSE_CHIMNEY_WINDOW, "house_chimney_window", "House chimney window" },
		eii{ ICON_HOUSE_CIRCLE_CHECK, "house_circle_check", "House circle check" },
		eii{ ICON_HOUSE_CIRCLE_EXCLAMATION, "house_circle_exclamation", "House circle exclamation" },
		eii{ ICON_HOUSE_CIRCLE_XMARK, "house_circle_xmark", "House circle xmark" },
		eii{ ICON_HOUSE_CRACK, "house_crack", "House crack" },
		eii{ ICON_HOUSE_FIRE, "house_fire", "House fire" },
		eii{ ICON_HOUSE_FLAG, "house_flag", "House flag" },
		eii{ ICON_HOUSE_FLOOD_WATER, "house_flood_water", "House flood water" },
		eii{ ICON_HOUSE_FLOOD_WATER_CIRCLE_ARROW_RIGHT, "house_flood_water_circle_arrow_right", "House flood water circle arrow right" },
		eii{ ICON_HOUSE_LAPTOP, "house_laptop", "House laptop" },
		eii{ ICON_HOUSE_LOCK, "house_lock", "House lock" },
		eii{ ICON_HOUSE_MEDICAL, "house_medical", "House medical" },
		eii{ ICON_HOUSE_MEDICAL_CIRCLE_CHECK, "house_medical_circle_check", "House medical circle check" },
		eii{ ICON_HOUSE_MEDICAL_CIRCLE_EXCLAMATION, "house_medical_circle_exclamation", "House medical circle exclamation" },
		eii{ ICON_HOUSE_MEDICAL_CIRCLE_XMARK, "house_medical_circle_xmark", "House medical circle xmark" },
		eii{ ICON_HOUSE_MEDICAL_FLAG, "house_medical_flag", "House medical flag" },
		eii{ ICON_HOUSE_SIGNAL, "house_signal", "House signal" },
		eii{ ICON_HOUSE_TSUNAMI, "house_tsunami", "House tsunami" },
		eii{ ICON_HOUSE_USER, "house_user", "House user" },
		eii{ ICON_HRYVNIA_SIGN, "hryvnia_sign", "Hryvnia sign" },
		eii{ ICON_HURRICANE, "hurricane", "Hurricane" },
		eii{ ICON_I_CURSOR, "i_cursor", "I cursor" },
		eii{ ICON_ICE_CREAM, "ice_cream", "Ice cream" },
		eii{ ICON_ICICLES, "icicles", "Icicles" },
		eii{ ICON_ICONS, "icons", "Icons" },
		eii{ ICON_ID_BADGE, "id_badge", "Id badge" },
		eii{ ICON_ID_CARD, "id_card", "Id card" },
		eii{ ICON_ID_CARD_CLIP, "id_card_clip", "Id card clip" },
		eii{ ICON_IGLOO, "igloo", "Igloo" },
		eii{ ICON_IMAGE, "image", "Image" },
		eii{ ICON_IMAGE_PORTRAIT, "image_portrait", "Image portrait" },
		eii{ ICON_IMAGES, "images", "Images" },
		eii{ ICON_INBOX, "inbox", "Inbox" },
		eii{ ICON_INDENT, "indent", "Indent" },
		eii{ ICON_INDIAN_RUPEE_SIGN, "indian_rupee_sign", "Indian rupee sign" },
		eii{ ICON_INDUSTRY, "industry", "Industry" },
		eii{ ICON_INFINITY, "infinity", "Infinity" },
		eii{ ICON_INFO, "info", "Info" },
		eii{ ICON_ITALIC, "italic", "Italic" },
		eii{ ICON_JAR, "jar", "Jar" },
		eii{ ICON_JAR_WHEAT, "jar_wheat", "Jar wheat" },
		eii{ ICON_JEDI, "jedi", "Jedi" },
		eii{ ICON_JET_FIGHTER, "jet_fighter", "Jet fighter" },
		eii{ ICON_JET_FIGHTER_UP, "jet_fighter_up", "Jet fighter up" },
		eii{ ICON_JOINT, "joint", "Joint" },
		eii{ ICON_JUG_DETERGENT, "jug_detergent", "Jug detergent" },
		eii{ ICON_KAABA, "kaaba", "Kaaba" },
		eii{ ICON_KEY, "key", "Key" },
		eii{ ICON_KEYBOARD, "keyboard", "Keyboard" },
		eii{ ICON_KHANDA, "khanda", "Khanda" },
		eii{ ICON_KIP_SIGN, "kip_sign", "Kip sign" },
		eii{ ICON_KIT_MEDICAL, "kit_medical", "Kit medical" },
		eii{ ICON_KITCHEN_SET, "kitchen_set", "Kitchen set" },
		eii{ ICON_KIWI_BIRD, "kiwi_bird", "Kiwi bird" },
		eii{ ICON_LAND_MINE_ON, "land_mine_on", "Land mine on" },
		eii{ ICON_LANDMARK, "landmark", "Landmark" },
		eii{ ICON_LANDMARK_DOME, "landmark_dome", "Landmark dome" },
		eii{ ICON_LANDMARK_FLAG, "landmark_flag", "Landmark flag" },
		eii{ ICON_LANGUAGE, "language", "Language" },
		eii{ ICON_LAPTOP, "laptop", "Laptop" },
		eii{ ICON_LAPTOP_CODE, "laptop_code", "Laptop code" },
		eii{ ICON_LAPTOP_FILE, "laptop_file", "Laptop file" },
		eii{ ICON_LAPTOP_MEDICAL, "laptop_medical", "Laptop medical" },
		eii{ ICON_LARI_SIGN, "lari_sign", "Lari sign" },
		eii{ ICON_LAYER_GROUP, "layer_group", "Layer group" },
		eii{ ICON_LEAF, "leaf", "Leaf" },
		eii{ ICON_LEFT_LONG, "left_long", "Left long" },
		eii{ ICON_LEFT_RIGHT, "left_right", "Left right" },
		eii{ ICON_LEMON, "lemon", "Lemon" },
		eii{ ICON_LESS_THAN_EQUAL, "less_than_equal", "Less than equal" },
		eii{ ICON_LIFE_RING, "life_ring", "Life ring" },
		eii{ ICON_LIGHTBULB, "lightbulb", "Lightbulb" },
		eii{ ICON_LINES_LEANING, "lines_leaning", "Lines leaning" },
		eii{ ICON_LINK, "link", "Link" },
		eii{ ICON_LINK_SLASH, "link_slash", "Link slash" },
		eii{ ICON_LIRA_SIGN, "lira_sign", "Lira sign" },
		eii{ ICON_LIST, "list", "List" },
		eii{ ICON_LIST_CHECK, "list_check", "List check" },
		eii{ ICON_LIST_OL, "list_ol", "List ol" },
		eii{ ICON_LIST_UL, "list_ul", "List ul" },
		eii{ ICON_LITECOIN_SIGN, "litecoin_sign", "Litecoin sign" },
		eii{ ICON_LOCATION_ARROW, "location_arrow", "Location arrow" },
		eii{ ICON_LOCATION_CROSSHAIRS, "location_crosshairs", "Location crosshairs" },
		eii{ ICON_LOCATION_DOT, "location_dot", "Location dot" },
		eii{ ICON_LOCATION_PIN, "location_pin", "Location pin" },
		eii{ ICON_LOCATION_PIN_LOCK, "location_pin_lock", "Location pin lock" },
		eii{ ICON_LOCK, "lock", "Lock" },
		eii{ ICON_LOCK_OPEN, "lock_open", "Lock open" },
		eii{ ICON_LOCUST, "locust", "Locust" },
		eii{ ICON_LUNGS, "lungs", "Lungs" },
		eii{ ICON_LUNGS_VIRUS, "lungs_virus", "Lungs virus" },
		eii{ ICON_MAGNET, "magnet", "Magnet" },
		eii{ ICON_MAGNIFYING_GLASS, "magnifying_glass", "Magnifying glass" },
		eii{ ICON_MAGNIFYING_GLASS_ARROW_RIGHT, "magnifying_glass_arrow_right", "Magnifying glass arrow right" },
		eii{ ICON_MAGNIFYING_GLASS_CHART, "magnifying_glass_chart", "Magnifying glass chart" },
		eii{ ICON_MAGNIFYING_GLASS_DOLLAR, "magnifying_glass_dollar", "Magnifying glass dollar" },
		eii{ ICON_MAGNIFYING_GLASS_LOCATION, "magnifying_glass_location", "Magnifying glass location" },
		eii{ ICON_MAGNIFYING_GLASS_MINUS, "magnifying_glass_minus", "Magnifying glass minus" },
		eii{ ICON_MAGNIFYING_GLASS_PLUS, "magnifying_glass_plus", "Magnifying glass plus" },
		eii{ ICON_MANAT_SIGN, "manat_sign", "Manat sign" },
		eii{ ICON_MAP, "map", "Map" },
		eii{ ICON_MAP_LOCATION, "map_location", "Map location" },
		eii{ ICON_MAP_LOCATION_DOT, "map_location_dot", "Map location dot" },
		eii{ ICON_MAP_PIN, "map_pin", "Map pin" },
		eii{ ICON_MARKER, "marker", "Marker" },
		eii{ ICON_MARS, "mars", "Mars" },
		eii{ ICON_MARS_AND_VENUS, "mars_and_venus", "Mars and venus" },
		eii{ ICON_MARS_AND_VENUS_BURST, "mars_and_venus_burst", "Mars and venus burst" },
		eii{ ICON_MARS_DOUBLE, "mars_double", "Mars double" },
		eii{ ICON_MARS_STROKE, "mars_stroke", "Mars stroke" },
		eii{ ICON_MARS_STROKE_RIGHT, "mars_stroke_right", "Mars stroke right" },
		eii{ ICON_MARS_STROKE_UP, "mars_stroke_up", "Mars stroke up" },
		eii{ ICON_MARTINI_GLASS, "martini_glass", "Martini glass" },
		eii{ ICON_MARTINI_GLASS_CITRUS, "martini_glass_citrus", "Martini glass citrus" },
		eii{ ICON_MARTINI_GLASS_EMPTY, "martini_glass_empty", "Martini glass empty" },
		eii{ ICON_MASK, "mask", "Mask" },
		eii{ ICON_MASK_FACE, "mask_face", "Mask face" },
		eii{ ICON_MASK_VENTILATOR, "mask_ventilator", "Mask ventilator" },
		eii{ ICON_MASKS_THEATER, "masks_theater", "Masks theater" },
		eii{ ICON_MATTRESS_PILLOW, "mattress_pillow", "Mattress pillow" },
		eii{ ICON_MAXIMIZE, "maximize", "Maximize" },
		eii{ ICON_MEDAL, "medal", "Medal" },
		eii{ ICON_MEMORY, "memory", "Memory" },
		eii{ ICON_MENORAH, "menorah", "Menorah" },
		eii{ ICON_MERCURY, "mercury", "Mercury" },
		eii{ ICON_MESSAGE, "message", "Message" },
		eii{ ICON_METEOR, "meteor", "Meteor" },
		eii{ ICON_MICROCHIP, "microchip", "Microchip" },
		eii{ ICON_MICROPHONE, "microphone", "Microphone" },
		eii{ ICON_MICROPHONE_LINES, "microphone_lines", "Microphone lines" },
		eii{ ICON_MICROPHONE_LINES_SLASH, "microphone_lines_slash", "Microphone lines slash" },
		eii{ ICON_MICROPHONE_SLASH, "microphone_slash", "Microphone slash" },
		eii{ ICON_MICROSCOPE, "microscope", "Microscope" },
		eii{ ICON_MILL_SIGN, "mill_sign", "Mill sign" },
		eii{ ICON_MINIMIZE, "minimize", "Minimize" },
		eii{ ICON_MINUS, "minus", "Minus" },
		eii{ ICON_MITTEN, "mitten", "Mitten" },
		eii{ ICON_MOBILE, "mobile", "Mobile" },
		eii{ ICON_MOBILE_BUTTON, "mobile_button", "Mobile button" },
		eii{ ICON_MOBILE_RETRO, "mobile_retro", "Mobile retro" },
		eii{ ICON_MOBILE_SCREEN, "mobile_screen", "Mobile screen" },
		eii{ ICON_MOBILE_SCREEN_BUTTON, "mobile_screen_button", "Mobile screen button" },
		eii{ ICON_MONEY_BILL, "money_bill", "Money bill" },
		eii{ ICON_MONEY_BILL_1, "money_bill_1", "Money bill 1" },
		eii{ ICON_MONEY_BILL_1_WAVE, "money_bill_1_wave", "Money bill 1 wave" },
		eii{ ICON_MONEY_BILL_TRANSFER, "money_bill_transfer", "Money bill transfer" },
		eii{ ICON_MONEY_BILL_TREND_UP, "money_bill_trend_up", "Money bill trend up" },
		eii{ ICON_MONEY_BILL_WAVE, "money_bill_wave", "Money bill wave" },
		eii{ ICON_MONEY_BILL_WHEAT, "money_bill_wheat", "Money bill wheat" },
		eii{ ICON_MONEY_BILLS, "money_bills", "Money bills" },
		eii{ ICON_MONEY_CHECK, "money_check", "Money check" },
		eii{ ICON_MONEY_CHECK_DOLLAR, "money_check_dollar", "Money check dollar" },
		eii{ ICON_MONUMENT, "monument", "Monument" },
		eii{ ICON_MOON, "moon", "Moon" },
		eii{ ICON_MORTAR_PESTLE, "mortar_pestle", "Mortar pestle" },
		eii{ ICON_MOSQUE, "mosque", "Mosque" },
		eii{ ICON_MOSQUITO, "mosquito", "Mosquito" },
		eii{ ICON_MOSQUITO_NET, "mosquito_net", "Mosquito net" },
		eii{ ICON_MOTORCYCLE, "motorcycle", "Motorcycle" },
		eii{ ICON_MOUND, "mound", "Mound" },
		eii{ ICON_MOUNTAIN, "mountain", "Mountain" },
		eii{ ICON_MOUNTAIN_CITY, "mountain_city", "Mountain city" },
		eii{ ICON_MOUNTAIN_SUN, "mountain_sun", "Mountain sun" },
		eii{ ICON_MUG_HOT, "mug_hot", "Mug hot" },
		eii{ ICON_MUG_SAUCER, "mug_saucer", "Mug saucer" },
		eii{ ICON_MUSIC, "music", "Music" },
		eii{ ICON_NAIRA_SIGN, "naira_sign", "Naira sign" },
		eii{ ICON_NETWORK_WIRED, "network_wired", "Network wired" },
		eii{ ICON_NEUTER, "neuter", "Neuter" },
		eii{ ICON_NEWSPAPER, "newspaper", "Newspaper" },
		eii{ ICON_NOT_EQUAL, "not_equal", "Not equal" },
		eii{ ICON_NOTDEF, "notdef", "Notdef" },
		eii{ ICON_NOTE_STICKY, "note_sticky", "Note sticky" },
		eii{ ICON_NOTES_MEDICAL, "notes_medical", "Notes medical" },
		eii{ ICON_OBJECT_GROUP, "object_group", "Object group" },
		eii{ ICON_OBJECT_UNGROUP, "object_ungroup", "Object ungroup" },
		eii{ ICON_OIL_CAN, "oil_can", "Oil can" },
		eii{ ICON_OIL_WELL, "oil_well", "Oil well" },
		eii{ ICON_OM, "om", "Om" },
		eii{ ICON_OTTER, "otter", "Otter" },
		eii{ ICON_OUTDENT, "outdent", "Outdent" },
		eii{ ICON_PAGER, "pager", "Pager" },
		eii{ ICON_PAINT_ROLLER, "paint_roller", "Paint roller" },
		eii{ ICON_PAINTBRUSH, "paintbrush", "Paintbrush" },
		eii{ ICON_PALETTE, "palette", "Palette" },
		eii{ ICON_PALLET, "pallet", "Pallet" },
		eii{ ICON_PANORAMA, "panorama", "Panorama" },
		eii{ ICON_PAPER_PLANE, "paper_plane", "Paper plane" },
		eii{ ICON_PAPERCLIP, "paperclip", "Paperclip" },
		eii{ ICON_PARACHUTE_BOX, "parachute_box", "Parachute box" },
		eii{ ICON_PARAGRAPH, "paragraph", "Paragraph" },
		eii{ ICON_PASSPORT, "passport", "Passport" },
		eii{ ICON_PASTE, "paste", "Paste" },
		eii{ ICON_PAUSE, "pause", "Pause" },
		eii{ ICON_PAW, "paw", "Paw" },
		eii{ ICON_PEACE, "peace", "Peace" },
		eii{ ICON_PEN, "pen", "Pen" },
		eii{ ICON_PEN_CLIP, "pen_clip", "Pen clip" },
		eii{ ICON_PEN_FANCY, "pen_fancy", "Pen fancy" },
		eii{ ICON_PEN_NIB, "pen_nib", "Pen nib" },
		eii{ ICON_PEN_RULER, "pen_ruler", "Pen ruler" },
		eii{ ICON_PEN_TO_SQUARE, "pen_to_square", "Pen to square" },
		eii{ ICON_PENCIL, "pencil", "Pencil" },
		eii{ ICON_PEOPLE_ARROWS, "people_arrows", "People arrows" },
		eii{ ICON_PEOPLE_CARRY_BOX, "people_carry_box", "People carry box" },
		eii{ ICON_PEOPLE_GROUP, "people_group", "People group" },
		eii{ ICON_PEOPLE_LINE, "people_line", "People line" },
		eii{ ICON_PEOPLE_PULLING, "people_pulling", "People pulling" },
		eii{ ICON_PEOPLE_ROBBERY, "people_robbery", "People robbery" },
		eii{ ICON_PEOPLE_ROOF, "people_roof", "People roof" },
		eii{ ICON_PEPPER_HOT, "pepper_hot", "Pepper hot" },
		eii{ ICON_PERSON, "person", "Person" },
		eii{ ICON_PERSON_ARROW_DOWN_TO_LINE, "person_arrow_down_to_line", "Person arrow down to line" },
		eii{ ICON_PERSON_ARROW_UP_FROM_LINE, "person_arrow_up_from_line", "Person arrow up from line" },
		eii{ ICON_PERSON_BIKING, "person_biking", "Person biking" },
		eii{ ICON_PERSON_BOOTH, "person_booth", "Person booth" },
		eii{ ICON_PERSON_BREASTFEEDING, "person_breastfeeding", "Person breastfeeding" },
		eii{ ICON_PERSON_BURST, "person_burst", "Person burst" },
		eii{ ICON_PERSON_CANE, "person_cane", "Person cane" },
		eii{ ICON_PERSON_CHALKBOARD, "person_chalkboard", "Person chalkboard" },
		eii{ ICON_PERSON_CIRCLE_CHECK, "person_circle_check", "Person circle check" },
		eii{ ICON_PERSON_CIRCLE_EXCLAMATION, "person_circle_exclamation", "Person circle exclamation" },
		eii{ ICON_PERSON_CIRCLE_MINUS, "person_circle_minus", "Person circle minus" },
		eii{ ICON_PERSON_CIRCLE_PLUS, "person_circle_plus", "Person circle plus" },
		eii{ ICON_PERSON_CIRCLE_QUESTION, "person_circle_question", "Person circle question" },
		eii{ ICON_PERSON_CIRCLE_XMARK, "person_circle_xmark", "Person circle xmark" },
		eii{ ICON_PERSON_DIGGING, "person_digging", "Person digging" },
		eii{ ICON_PERSON_DOTS_FROM_LINE, "person_dots_from_line", "Person dots from line" },
		eii{ ICON_PERSON_DRESS, "person_dress", "Person dress" },
		eii{ ICON_PERSON_DRESS_BURST, "person_dress_burst", "Person dress burst" },
		eii{ ICON_PERSON_DROWNING, "person_drowning", "Person drowning" },
		eii{ ICON_PERSON_FALLING, "person_falling", "Person falling" },
		eii{ ICON_PERSON_FALLING_BURST, "person_falling_burst", "Person falling burst" },
		eii{ ICON_PERSON_HALF_DRESS, "person_half_dress", "Person half dress" },
		eii{ ICON_PERSON_HARASSING, "person_harassing", "Person harassing" },
		eii{ ICON_PERSON_HIKING, "person_hiking", "Person hiking" },
		eii{ ICON_PERSON_MILITARY_POINTING, "person_military_pointing", "Person military pointing" },
		eii{ ICON_PERSON_MILITARY_RIFLE, "person_military_rifle", "Person military rifle" },
		eii{ ICON_PERSON_MILITARY_TO_PERSON, "person_military_to_person", "Person military to person" },
		eii{ ICON_PERSON_PRAYING, "person_praying", "Person praying" },
		eii{ ICON_PERSON_PREGNANT, "person_pregnant", "Person pregnant" },
		eii{ ICON_PERSON_RAYS, "person_rays", "Person rays" },
		eii{ ICON_PERSON_RIFLE, "person_rifle", "Person rifle" },
		eii{ ICON_PERSON_RUNNING, "person_running", "Person running" },
		eii{ ICON_PERSON_SHELTER, "person_shelter", "Person shelter" },
		eii{ ICON_PERSON_SKATING, "person_skating", "Person skating" },
		eii{ ICON_PERSON_SKIING, "person_skiing", "Person skiing" },
		eii{ ICON_PERSON_SKIING_NORDIC, "person_skiing_nordic", "Person skiing nordic" },
		eii{ ICON_PERSON_SNOWBOARDING, "person_snowboarding", "Person snowboarding" },
		eii{ ICON_PERSON_SWIMMING, "person_swimming", "Person swimming" },
		eii{ ICON_PERSON_THROUGH_WINDOW, "person_through_window", "Person through window" },
		eii{ ICON_PERSON_WALKING, "person_walking", "Person walking" },
		eii{ ICON_PERSON_WALKING_ARROW_LOOP_LEFT, "person_walking_arrow_loop_left", "Person walking arrow loop left" },
		eii{ ICON_PERSON_WALKING_ARROW_RIGHT, "person_walking_arrow_right", "Person walking arrow right" },
		eii{ ICON_PERSON_WALKING_DASHED_LINE_ARROW_RIGHT, "person_walking_dashed_line_arrow_right", "Person walking dashed line arrow right" },
		eii{ ICON_PERSON_WALKING_LUGGAGE, "person_walking_luggage", "Person walking luggage" },
		eii{ ICON_PERSON_WALKING_WITH_CANE, "person_walking_with_cane", "Person walking with cane" },
		eii{ ICON_PESETA_SIGN, "peseta_sign", "Peseta sign" },
		eii{ ICON_PESO_SIGN, "peso_sign", "Peso sign" },
		eii{ ICON_PHONE, "phone", "Phone" },
		eii{ ICON_PHONE_FLIP, "phone_flip", "Phone flip" },
		eii{ ICON_PHONE_SLASH, "phone_slash", "Phone slash" },
		eii{ ICON_PHONE_VOLUME, "phone_volume", "Phone volume" },
		eii{ ICON_PHOTO_FILM, "photo_film", "Photo film" },
		eii{ ICON_PIGGY_BANK, "piggy_bank", "Piggy bank" },
		eii{ ICON_PILLS, "pills", "Pills" },
		eii{ ICON_PIZZA_SLICE, "pizza_slice", "Pizza slice" },
		eii{ ICON_PLACE_OF_WORSHIP, "place_of_worship", "Place of worship" },
		eii{ ICON_PLANE, "plane", "Plane" },
		eii{ ICON_PLANE_ARRIVAL, "plane_arrival", "Plane arrival" },
		eii{ ICON_PLANE_CIRCLE_CHECK, "plane_circle_check", "Plane circle check" },
		eii{ ICON_PLANE_CIRCLE_EXCLAMATION, "plane_circle_exclamation", "Plane circle exclamation" },
		eii{ ICON_PLANE_CIRCLE_XMARK, "plane_circle_xmark", "Plane circle xmark" },
		eii{ ICON_PLANE_DEPARTURE, "plane_departure", "Plane departure" },
		eii{ ICON_PLANE_LOCK, "plane_lock", "Plane lock" },
		eii{ ICON_PLANE_SLASH, "plane_slash", "Plane slash" },
		eii{ ICON_PLANE_UP, "plane_up", "Plane up" },
		eii{ ICON_PLANT_WILT, "plant_wilt", "Plant wilt" },
		eii{ ICON_PLATE_WHEAT, "plate_wheat", "Plate wheat" },
		eii{ ICON_PLAY, "play", "Play" },
		eii{ ICON_PLUG, "plug", "Plug" },
		eii{ ICON_PLUG_CIRCLE_BOLT, "plug_circle_bolt", "Plug circle bolt" },
		eii{ ICON_PLUG_CIRCLE_CHECK, "plug_circle_check", "Plug circle check" },
		eii{ ICON_PLUG_CIRCLE_EXCLAMATION, "plug_circle_exclamation", "Plug circle exclamation" },
		eii{ ICON_PLUG_CIRCLE_MINUS, "plug_circle_minus", "Plug circle minus" },
		eii{ ICON_PLUG_CIRCLE_PLUS, "plug_circle_plus", "Plug circle plus" },
		eii{ ICON_PLUG_CIRCLE_XMARK, "plug_circle_xmark", "Plug circle xmark" },
		eii{ ICON_PLUS_MINUS, "plus_minus", "Plus minus" },
		eii{ ICON_PODCAST, "podcast", "Podcast" },
		eii{ ICON_POO, "poo", "Poo" },
		eii{ ICON_POO_STORM, "poo_storm", "Poo storm" },
		eii{ ICON_POOP, "poop", "Poop" },
		eii{ ICON_POWER_OFF, "power_off", "Power off" },
		eii{ ICON_PRESCRIPTION, "prescription", "Prescription" },
		eii{ ICON_PRESCRIPTION_BOTTLE, "prescription_bottle", "Prescription bottle" },
		eii{ ICON_PRESCRIPTION_BOTTLE_MEDICAL, "prescription_bottle_medical", "Prescription bottle medical" },
		eii{ ICON_PRINT, "print", "Print" },
		eii{ ICON_PUMP_MEDICAL, "pump_medical", "Pump medical" },
		eii{ ICON_PUMP_SOAP, "pump_soap", "Pump soap" },
		eii{ ICON_PUZZLE_PIECE, "puzzle_piece", "Puzzle piece" },
		eii{ ICON_QRCODE, "qrcode", "Qrcode" },
		eii{ ICON_QUOTE_LEFT, "quote_left", "Quote left" },
		eii{ ICON_QUOTE_RIGHT, "quote_right", "Quote right" },
		eii{ ICON_RADIATION, "radiation", "Radiation" },
		eii{ ICON_RADIO, "radio", "Radio" },
		eii{ ICON_RAINBOW, "rainbow", "Rainbow" },
		eii{ ICON_RANKING_STAR, "ranking_star", "Ranking star" },
		eii{ ICON_RECEIPT, "receipt", "Receipt" },
		eii{ ICON_RECORD_VINYL, "record_vinyl", "Record vinyl" },
		eii{ ICON_RECTANGLE_AD, "rectangle_ad", "Rectangle ad" },
		eii{ ICON_RECTANGLE_LIST, "rectangle_list", "Rectangle list" },
		eii{ ICON_RECTANGLE_XMARK, "rectangle_xmark", "Rectangle xmark" },
		eii{ ICON_RECYCLE, "recycle", "Recycle" },
		eii{ ICON_REGISTERED, "registered", "Registered" },
		eii{ ICON_REPEAT, "repeat", "Repeat" },
		eii{ ICON_REPLY, "reply", "Reply" },
		eii{ ICON_REPLY_ALL, "reply_all", "Reply all" },
		eii{ ICON_REPUBLICAN, "republican", "Republican" },
		eii{ ICON_RESTROOM, "restroom", "Restroom" },
		eii{ ICON_RETWEET, "retweet", "Retweet" },
		eii{ ICON_RIBBON, "ribbon", "Ribbon" },
		eii{ ICON_RIGHT_FROM_BRACKET, "right_from_bracket", "Right from bracket" },
		eii{ ICON_RIGHT_LEFT, "right_left", "Right left" },
		eii{ ICON_RIGHT_LONG, "right_long", "Right long" },
		eii{ ICON_RIGHT_TO_BRACKET, "right_to_bracket", "Right to bracket" },
		eii{ ICON_RING, "ring", "Ring" },
		eii{ ICON_ROAD, "road", "Road" },
		eii{ ICON_ROAD_BARRIER, "road_barrier", "Road barrier" },
		eii{ ICON_ROAD_BRIDGE, "road_bridge", "Road bridge" },
		eii{ ICON_ROAD_CIRCLE_CHECK, "road_circle_check", "Road circle check" },
		eii{ ICON_ROAD_CIRCLE_EXCLAMATION, "road_circle_exclamation", "Road circle exclamation" },
		eii{ ICON_ROAD_CIRCLE_XMARK, "road_circle_xmark", "Road circle xmark" },
		eii{ ICON_ROAD_LOCK, "road_lock", "Road lock" },
		eii{ ICON_ROAD_SPIKES, "road_spikes", "Road spikes" },
		eii{ ICON_ROBOT, "robot", "Robot" },
		eii{ ICON_ROCKET, "rocket", "Rocket" },
		eii{ ICON_ROTATE, "rotate", "Rotate" },
		eii{ ICON_ROTATE_LEFT, "rotate_left", "Rotate left" },
		eii{ ICON_ROTATE_RIGHT, "rotate_right", "Rotate right" },
		eii{ ICON_ROUTE, "route", "Route" },
		eii{ ICON_RSS, "rss", "Rss" },
		eii{ ICON_RUBLE_SIGN, "ruble_sign", "Ruble sign" },
		eii{ ICON_RUG, "rug", "Rug" },
		eii{ ICON_RULER, "ruler", "Ruler" },
		eii{ ICON_RULER_COMBINED, "ruler_combined", "Ruler combined" },
		eii{ ICON_RULER_HORIZONTAL, "ruler_horizontal", "Ruler horizontal" },
		eii{ ICON_RULER_VERTICAL, "ruler_vertical", "Ruler vertical" },
		eii{ ICON_RUPEE_SIGN, "rupee_sign", "Rupee sign" },
		eii{ ICON_RUPIAH_SIGN, "rupiah_sign", "Rupiah sign" },
		eii{ ICON_SACK_DOLLAR, "sack_dollar", "Sack dollar" },
		eii{ ICON_SACK_XMARK, "sack_xmark", "Sack xmark" },
		eii{ ICON_SAILBOAT, "sailboat", "Sailboat" },
		eii{ ICON_SATELLITE, "satellite", "Satellite" },
		eii{ ICON_SATELLITE_DISH, "satellite_dish", "Satellite dish" },
		eii{ ICON_SCALE_BALANCED, "scale_balanced", "Scale balanced" },
		eii{ ICON_SCALE_UNBALANCED, "scale_unbalanced", "Scale unbalanced" },
		eii{ ICON_SCALE_UNBALANCED_FLIP, "scale_unbalanced_flip", "Scale unbalanced flip" },
		eii{ ICON_SCHOOL, "school", "School" },
		eii{ ICON_SCHOOL_CIRCLE_CHECK, "school_circle_check", "School circle check" },
		eii{ ICON_SCHOOL_CIRCLE_EXCLAMATION, "school_circle_exclamation", "School circle exclamation" },
		eii{ ICON_SCHOOL_CIRCLE_XMARK, "school_circle_xmark", "School circle xmark" },
		eii{ ICON_SCHOOL_FLAG, "school_flag", "School flag" },
		eii{ ICON_SCHOOL_LOCK, "school_lock", "School lock" },
		eii{ ICON_SCISSORS, "scissors", "Scissors" },
		eii{ ICON_SCREWDRIVER, "screwdriver", "Screwdriver" },
		eii{ ICON_SCREWDRIVER_WRENCH, "screwdriver_wrench", "Screwdriver wrench" },
		eii{ ICON_SCROLL, "scroll", "Scroll" },
		eii{ ICON_SCROLL_TORAH, "scroll_torah", "Scroll torah" },
		eii{ ICON_SD_CARD, "sd_card", "Sd card" },
		eii{ ICON_SECTION, "section", "Section" },
		eii{ ICON_SEEDLING, "seedling", "Seedling" },
		eii{ ICON_SERVER, "server", "Server" },
		eii{ ICON_SHAPES, "shapes", "Shapes" },
		eii{ ICON_SHARE, "share", "Share" },
		eii{ ICON_SHARE_FROM_SQUARE, "share_from_square", "Share from square" },
		eii{ ICON_SHARE_NODES, "share_nodes", "Share nodes" },
		eii{ ICON_SHEET_PLASTIC, "sheet_plastic", "Sheet plastic" },
		eii{ ICON_SHEKEL_SIGN, "shekel_sign", "Shekel sign" },
		eii{ ICON_SHIELD, "shield", "Shield" },
		eii{ ICON_SHIELD_CAT, "shield_cat", "Shield cat" },
		eii{ ICON_SHIELD_DOG, "shield_dog", "Shield dog" },
		eii{ ICON_SHIELD_HALVED, "shield_halved", "Shield halved" },
		eii{ ICON_SHIELD_HEART, "shield_heart", "Shield heart" },
		eii{ ICON_SHIELD_VIRUS, "shield_virus", "Shield virus" },
		eii{ ICON_SHIP, "ship", "Ship" },
		eii{ ICON_SHIRT, "shirt", "Shirt" },
		eii{ ICON_SHOE_PRINTS, "shoe_prints", "Shoe prints" },
		eii{ ICON_SHOP, "shop", "Shop" },
		eii{ ICON_SHOP_LOCK, "shop_lock", "Shop lock" },
		eii{ ICON_SHOP_SLASH, "shop_slash", "Shop slash" },
		eii{ ICON_SHOWER, "shower", "Shower" },
		eii{ ICON_SHRIMP, "shrimp", "Shrimp" },
		eii{ ICON_SHUFFLE, "shuffle", "Shuffle" },
		eii{ ICON_SHUTTLE_SPACE, "shuttle_space", "Shuttle space" },
		eii{ ICON_SIGN_HANGING, "sign_hanging", "Sign hanging" },
		eii{ ICON_SIGNAL, "signal", "Signal" },
		eii{ ICON_SIGNATURE, "signature", "Signature" },
		eii{ ICON_SIGNS_POST, "signs_post", "Signs post" },
		eii{ ICON_SIM_CARD, "sim_card", "Sim card" },
		eii{ ICON_SINK, "sink", "Sink" },
		eii{ ICON_SITEMAP, "sitemap", "Sitemap" },
		eii{ ICON_SKULL, "skull", "Skull" },
		eii{ ICON_SKULL_CROSSBONES, "skull_crossbones", "Skull crossbones" },
		eii{ ICON_SLASH, "slash", "Slash" },
		eii{ ICON_SLEIGH, "sleigh", "Sleigh" },
		eii{ ICON_SLIDERS, "sliders", "Sliders" },
		eii{ ICON_SMOG, "smog", "Smog" },
		eii{ ICON_SMOKING, "smoking", "Smoking" },
		eii{ ICON_SNOWFLAKE, "snowflake", "Snowflake" },
		eii{ ICON_SNOWMAN, "snowman", "Snowman" },
		eii{ ICON_SNOWPLOW, "snowplow", "Snowplow" },
		eii{ ICON_SOAP, "soap", "Soap" },
		eii{ ICON_SOCKS, "socks", "Socks" },
		eii{ ICON_SOLAR_PANEL, "solar_panel", "Solar panel" },
		eii{ ICON_SORT, "sort", "Sort" },
		eii{ ICON_SORT_DOWN, "sort_down", "Sort down" },
		eii{ ICON_SORT_UP, "sort_up", "Sort up" },
		eii{ ICON_SPA, "spa", "Spa" },
		eii{ ICON_SPAGHETTI_MONSTER_FLYING, "spaghetti_monster_flying", "Spaghetti monster flying" },
		eii{ ICON_SPELL_CHECK, "spell_check", "Spell check" },
		eii{ ICON_SPIDER, "spider", "Spider" },
		eii{ ICON_SPINNER, "spinner", "Spinner" },
		eii{ ICON_SPLOTCH, "splotch", "Splotch" },
		eii{ ICON_SPOON, "spoon", "Spoon" },
		eii{ ICON_SPRAY_CAN, "spray_can", "Spray can" },
		eii{ ICON_SPRAY_CAN_SPARKLES, "spray_can_sparkles", "Spray can sparkles" },
		eii{ ICON_SQUARE, "square", "Square" },
		eii{ ICON_SQUARE_ARROW_UP_RIGHT, "square_arrow_up_right", "Square arrow up right" },
		eii{ ICON_SQUARE_CARET_DOWN, "square_caret_down", "Square caret down" },
		eii{ ICON_SQUARE_CARET_LEFT, "square_caret_left", "Square caret left" },
		eii{ ICON_SQUARE_CARET_RIGHT, "square_caret_right", "Square caret right" },
		eii{ ICON_SQUARE_CARET_UP, "square_caret_up", "Square caret up" },
		eii{ ICON_SQUARE_CHECK, "square_check", "Square check" },
		eii{ ICON_SQUARE_ENVELOPE, "square_envelope", "Square envelope" },
		eii{ ICON_SQUARE_FULL, "square_full", "Square full" },
		eii{ ICON_SQUARE_H, "square_h", "Square h" },
		eii{ ICON_SQUARE_MINUS, "square_minus", "Square minus" },
		eii{ ICON_SQUARE_NFI, "square_nfi", "Square nfi" },
		eii{ ICON_SQUARE_PARKING, "square_parking", "Square parking" },
		eii{ ICON_SQUARE_PEN, "square_pen", "Square pen" },
		eii{ ICON_SQUARE_PERSON_CONFINED, "square_person_confined", "Square person confined" },
		eii{ ICON_SQUARE_PHONE, "square_phone", "Square phone" },
		eii{ ICON_SQUARE_PHONE_FLIP, "square_phone_flip", "Square phone flip" },
		eii{ ICON_SQUARE_PLUS, "square_plus", "Square plus" },
		eii{ ICON_SQUARE_POLL_HORIZONTAL, "square_poll_horizontal", "Square poll horizontal" },
		eii{ ICON_SQUARE_POLL_VERTICAL, "square_poll_vertical", "Square poll vertical" },
		eii{ ICON_SQUARE_ROOT_VARIABLE, "square_root_variable", "Square root variable" },
		eii{ ICON_SQUARE_RSS, "square_rss", "Square rss" },
		eii{ ICON_SQUARE_SHARE_NODES, "square_share_nodes", "Square share nodes" },
		eii{ ICON_SQUARE_UP_RIGHT, "square_up_right", "Square up right" },
		eii{ ICON_SQUARE_VIRUS, "square_virus", "Square virus" },
		eii{ ICON_SQUARE_XMARK, "square_xmark", "Square xmark" },
		eii{ ICON_STAFF_SNAKE, "staff_snake", "Staff snake" },
		eii{ ICON_STAIRS, "stairs", "Stairs" },
		eii{ ICON_STAMP, "stamp", "Stamp" },
		eii{ ICON_STAPLER, "stapler", "Stapler" },
		eii{ ICON_STAR, "star", "Star" },
		eii{ ICON_STAR_AND_CRESCENT, "star_and_crescent", "Star and crescent" },
		eii{ ICON_STAR_HALF, "star_half", "Star half" },
		eii{ ICON_STAR_HALF_STROKE, "star_half_stroke", "Star half stroke" },
		eii{ ICON_STAR_OF_DAVID, "star_of_david", "Star of david" },
		eii{ ICON_STAR_OF_LIFE, "star_of_life", "Star of life" },
		eii{ ICON_STERLING_SIGN, "sterling_sign", "Sterling sign" },
		eii{ ICON_STETHOSCOPE, "stethoscope", "Stethoscope" },
		eii{ ICON_STOP, "stop", "Stop" },
		eii{ ICON_STOPWATCH, "stopwatch", "Stopwatch" },
		eii{ ICON_STOPWATCH_20, "stopwatch_20", "Stopwatch 20" },
		eii{ ICON_STORE, "store", "Store" },
		eii{ ICON_STORE_SLASH, "store_slash", "Store slash" },
		eii{ ICON_STREET_VIEW, "street_view", "Street view" },
		eii{ ICON_STRIKETHROUGH, "strikethrough", "Strikethrough" },
		eii{ ICON_STROOPWAFEL, "stroopwafel", "Stroopwafel" },
		eii{ ICON_SUBSCRIPT, "subscript", "Subscript" },
		eii{ ICON_SUITCASE, "suitcase", "Suitcase" },
		eii{ ICON_SUITCASE_MEDICAL, "suitcase_medical", "Suitcase medical" },
		eii{ ICON_SUITCASE_ROLLING, "suitcase_rolling", "Suitcase rolling" },
		eii{ ICON_SUN, "sun", "Sun" },
		eii{ ICON_SUN_PLANT_WILT, "sun_plant_wilt", "Sun plant wilt" },
		eii{ ICON_SUPERSCRIPT, "superscript", "Superscript" },
		eii{ ICON_SWATCHBOOK, "swatchbook", "Swatchbook" },
		eii{ ICON_SYNAGOGUE, "synagogue", "Synagogue" },
		eii{ ICON_SYRINGE, "syringe", "Syringe" },
		eii{ ICON_TABLE, "table", "Table" },
		eii{ ICON_TABLE_CELLS, "table_cells", "Table cells" },
		eii{ ICON_TABLE_CELLS_COLUMN_LOCK, "table_cells_column_lock", "Table cells column lock" },
		eii{ ICON_TABLE_CELLS_LARGE, "table_cells_large", "Table cells large" },
		eii{ ICON_TABLE_CELLS_ROW_LOCK, "table_cells_row_lock", "Table cells row lock" },
		eii{ ICON_TABLE_COLUMNS, "table_columns", "Table columns" },
		eii{ ICON_TABLE_LIST, "table_list", "Table list" },
		eii{ ICON_TABLE_TENNIS_PADDLE_BALL, "table_tennis_paddle_ball", "Table tennis paddle ball" },
		eii{ ICON_TABLET, "tablet", "Tablet" },
		eii{ ICON_TABLET_BUTTON, "tablet_button", "Tablet button" },
		eii{ ICON_TABLET_SCREEN_BUTTON, "tablet_screen_button", "Tablet screen button" },
		eii{ ICON_TABLETS, "tablets", "Tablets" },
		eii{ ICON_TACHOGRAPH_DIGITAL, "tachograph_digital", "Tachograph digital" },
		eii{ ICON_TAG, "tag", "Tag" },
		eii{ ICON_TAGS, "tags", "Tags" },
		eii{ ICON_TAPE, "tape", "Tape" },
		eii{ ICON_TARP, "tarp", "Tarp" },
		eii{ ICON_TARP_DROPLET, "tarp_droplet", "Tarp droplet" },
		eii{ ICON_TAXI, "taxi", "Taxi" },
		eii{ ICON_TEETH, "teeth", "Teeth" },
		eii{ ICON_TEETH_OPEN, "teeth_open", "Teeth open" },
		eii{ ICON_TEMPERATURE_ARROW_DOWN, "temperature_arrow_down", "Temperature arrow down" },
		eii{ ICON_TEMPERATURE_ARROW_UP, "temperature_arrow_up", "Temperature arrow up" },
		eii{ ICON_TEMPERATURE_EMPTY, "temperature_empty", "Temperature empty" },
		eii{ ICON_TEMPERATURE_FULL, "temperature_full", "Temperature full" },
		eii{ ICON_TEMPERATURE_HALF, "temperature_half", "Temperature half" },
		eii{ ICON_TEMPERATURE_HIGH, "temperature_high", "Temperature high" },
		eii{ ICON_TEMPERATURE_LOW, "temperature_low", "Temperature low" },
		eii{ ICON_TEMPERATURE_QUARTER, "temperature_quarter", "Temperature quarter" },
		eii{ ICON_TEMPERATURE_THREE_QUARTERS, "temperature_three_quarters", "Temperature three quarters" },
		eii{ ICON_TENGE_SIGN, "tenge_sign", "Tenge sign" },
		eii{ ICON_TENT, "tent", "Tent" },
		eii{ ICON_TENT_ARROW_DOWN_TO_LINE, "tent_arrow_down_to_line", "Tent arrow down to line" },
		eii{ ICON_TENT_ARROW_LEFT_RIGHT, "tent_arrow_left_right", "Tent arrow left right" },
		eii{ ICON_TENT_ARROW_TURN_LEFT, "tent_arrow_turn_left", "Tent arrow turn left" },
		eii{ ICON_TENT_ARROWS_DOWN, "tent_arrows_down", "Tent arrows down" },
		eii{ ICON_TENTS, "tents", "Tents" },
		eii{ ICON_TERMINAL, "terminal", "Terminal" },
		eii{ ICON_TEXT_HEIGHT, "text_height", "Text height" },
		eii{ ICON_TEXT_SLASH, "text_slash", "Text slash" },
		eii{ ICON_TEXT_WIDTH, "text_width", "Text width" },
		eii{ ICON_THERMOMETER, "thermometer", "Thermometer" },
		eii{ ICON_THUMBS_DOWN, "thumbs_down", "Thumbs down" },
		eii{ ICON_THUMBS_UP, "thumbs_up", "Thumbs up" },
		eii{ ICON_THUMBTACK, "thumbtack", "Thumbtack" },
		eii{ ICON_TICKET, "ticket", "Ticket" },
		eii{ ICON_TICKET_SIMPLE, "ticket_simple", "Ticket simple" },
		eii{ ICON_TIMELINE, "timeline", "Timeline" },
		eii{ ICON_TOGGLE_OFF, "toggle_off", "Toggle off" },
		eii{ ICON_TOGGLE_ON, "toggle_on", "Toggle on" },
		eii{ ICON_TOILET, "toilet", "Toilet" },
		eii{ ICON_TOILET_PAPER, "toilet_paper", "Toilet paper" },
		eii{ ICON_TOILET_PAPER_SLASH, "toilet_paper_slash", "Toilet paper slash" },
		eii{ ICON_TOILET_PORTABLE, "toilet_portable", "Toilet portable" },
		eii{ ICON_TOILETS_PORTABLE, "toilets_portable", "Toilets portable" },
		eii{ ICON_TOOLBOX, "toolbox", "Toolbox" },
		eii{ ICON_TOOTH, "tooth", "Tooth" },
		eii{ ICON_TORII_GATE, "torii_gate", "Torii gate" },
		eii{ ICON_TORNADO, "tornado", "Tornado" },
		eii{ ICON_TOWER_BROADCAST, "tower_broadcast", "Tower broadcast" },
		eii{ ICON_TOWER_CELL, "tower_cell", "Tower cell" },
		eii{ ICON_TOWER_OBSERVATION, "tower_observation", "Tower observation" },
		eii{ ICON_TRACTOR, "tractor", "Tractor" },
		eii{ ICON_TRADEMARK, "trademark", "Trademark" },
		eii{ ICON_TRAFFIC_LIGHT, "traffic_light", "Traffic light" },
		eii{ ICON_TRAILER, "trailer", "Trailer" },
		eii{ ICON_TRAIN, "train", "Train" },
		eii{ ICON_TRAIN_SUBWAY, "train_subway", "Train subway" },
		eii{ ICON_TRAIN_TRAM, "train_tram", "Train tram" },
		eii{ ICON_TRANSGENDER, "transgender", "Transgender" },
		eii{ ICON_TRASH, "trash", "Trash" },
		eii{ ICON_TRASH_ARROW_UP, "trash_arrow_up", "Trash arrow up" },
		eii{ ICON_TRASH_CAN, "trash_can", "Trash can" },
		eii{ ICON_TRASH_CAN_ARROW_UP, "trash_can_arrow_up", "Trash can arrow up" },
		eii{ ICON_TREE, "tree", "Tree" },
		eii{ ICON_TREE_CITY, "tree_city", "Tree city" },
		eii{ ICON_TRIANGLE_EXCLAMATION, "triangle_exclamation", "Triangle exclamation" },
		eii{ ICON_TROPHY, "trophy", "Trophy" },
		eii{ ICON_TROWEL, "trowel", "Trowel" },
		eii{ ICON_TROWEL_BRICKS, "trowel_bricks", "Trowel bricks" },
		eii{ ICON_TRUCK, "truck", "Truck" },
		eii{ ICON_TRUCK_ARROW_RIGHT, "truck_arrow_right", "Truck arrow right" },
		eii{ ICON_TRUCK_DROPLET, "truck_droplet", "Truck droplet" },
		eii{ ICON_TRUCK_FAST, "truck_fast", "Truck fast" },
		eii{ ICON_TRUCK_FIELD, "truck_field", "Truck field" },
		eii{ ICON_TRUCK_FIELD_UN, "truck_field_un", "Truck field un" },
		eii{ ICON_TRUCK_FRONT, "truck_front", "Truck front" },
		eii{ ICON_TRUCK_MEDICAL, "truck_medical", "Truck medical" },
		eii{ ICON_TRUCK_MONSTER, "truck_monster", "Truck monster" },
		eii{ ICON_TRUCK_MOVING, "truck_moving", "Truck moving" },
		eii{ ICON_TRUCK_PICKUP, "truck_pickup", "Truck pickup" },
		eii{ ICON_TRUCK_PLANE, "truck_plane", "Truck plane" },
		eii{ ICON_TRUCK_RAMP_BOX, "truck_ramp_box", "Truck ramp box" },
		eii{ ICON_TTY, "tty", "Tty" },
		eii{ ICON_TURKISH_LIRA_SIGN, "turkish_lira_sign", "Turkish lira sign" },
		eii{ ICON_TURN_DOWN, "turn_down", "Turn down" },
		eii{ ICON_TURN_UP, "turn_up", "Turn up" },
		eii{ ICON_TV, "tv", "Tv" },
		eii{ ICON_UMBRELLA, "umbrella", "Umbrella" },
		eii{ ICON_UMBRELLA_BEACH, "umbrella_beach", "Umbrella beach" },
		eii{ ICON_UNDERLINE, "underline", "Underline" },
		eii{ ICON_UNIVERSAL_ACCESS, "universal_access", "Universal access" },
		eii{ ICON_UNLOCK, "unlock", "Unlock" },
		eii{ ICON_UNLOCK_KEYHOLE, "unlock_keyhole", "Unlock keyhole" },
		eii{ ICON_UP_DOWN, "up_down", "Up down" },
		eii{ ICON_UP_DOWN_LEFT_RIGHT, "up_down_left_right", "Up down left right" },
		eii{ ICON_UP_LONG, "up_long", "Up long" },
		eii{ ICON_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER, "up_right_and_down_left_from_center", "Up right and down left from center" },
		eii{ ICON_UP_RIGHT_FROM_SQUARE, "up_right_from_square", "Up right from square" },
		eii{ ICON_UPLOAD, "upload", "Upload" },
		eii{ ICON_USER, "user", "User" },
		eii{ ICON_USER_ASTRONAUT, "user_astronaut", "User astronaut" },
		eii{ ICON_USER_CHECK, "user_check", "User check" },
		eii{ ICON_USER_CLOCK, "user_clock", "User clock" },
		eii{ ICON_USER_DOCTOR, "user_doctor", "User doctor" },
		eii{ ICON_USER_GEAR, "user_gear", "User gear" },
		eii{ ICON_USER_GRADUATE, "user_graduate", "User graduate" },
		eii{ ICON_USER_GROUP, "user_group", "User group" },
		eii{ ICON_USER_INJURED, "user_injured", "User injured" },
		eii{ ICON_USER_LARGE, "user_large", "User large" },
		eii{ ICON_USER_LARGE_SLASH, "user_large_slash", "User large slash" },
		eii{ ICON_USER_LOCK, "user_lock", "User lock" },
		eii{ ICON_USER_MINUS, "user_minus", "User minus" },
		eii{ ICON_USER_NINJA, "user_ninja", "User ninja" },
		eii{ ICON_USER_NURSE, "user_nurse", "User nurse" },
		eii{ ICON_USER_PEN, "user_pen", "User pen" },
		eii{ ICON_USER_PLUS, "user_plus", "User plus" },
		eii{ ICON_USER_SECRET, "user_secret", "User secret" },
		eii{ ICON_USER_SHIELD, "user_shield", "User shield" },
		eii{ ICON_USER_SLASH, "user_slash", "User slash" },
		eii{ ICON_USER_TAG, "user_tag", "User tag" },
		eii{ ICON_USER_TIE, "user_tie", "User tie" },
		eii{ ICON_USER_XMARK, "user_xmark", "User xmark" },
		eii{ ICON_USERS, "users", "Users" },
		eii{ ICON_USERS_BETWEEN_LINES, "users_between_lines", "Users between lines" },
		eii{ ICON_USERS_GEAR, "users_gear", "Users gear" },
		eii{ ICON_USERS_LINE, "users_line", "Users line" },
		eii{ ICON_USERS_RAYS, "users_rays", "Users rays" },
		eii{ ICON_USERS_RECTANGLE, "users_rectangle", "Users rectangle" },
		eii{ ICON_USERS_SLASH, "users_slash", "Users slash" },
		eii{ ICON_USERS_VIEWFINDER, "users_viewfinder", "Users viewfinder" },
		eii{ ICON_UTENSILS, "utensils", "Utensils" },
		eii{ ICON_VAN_SHUTTLE, "van_shuttle", "Van shuttle" },
		eii{ ICON_VAULT, "vault", "Vault" },
		eii{ ICON_VECTOR_SQUARE, "vector_square", "Vector square" },
		eii{ ICON_VENUS, "venus", "Venus" },
		eii{ ICON_VENUS_DOUBLE, "venus_double", "Venus double" },
		eii{ ICON_VENUS_MARS, "venus_mars", "Venus mars" },
		eii{ ICON_VEST, "vest", "Vest" },
		eii{ ICON_VEST_PATCHES, "vest_patches", "Vest patches" },
		eii{ ICON_VIAL, "vial", "Vial" },
		eii{ ICON_VIAL_CIRCLE_CHECK, "vial_circle_check", "Vial circle check" },
		eii{ ICON_VIAL_VIRUS, "vial_virus", "Vial virus" },
		eii{ ICON_VIALS, "vials", "Vials" },
		eii{ ICON_VIDEO, "video", "Video" },
		eii{ ICON_VIDEO_SLASH, "video_slash", "Video slash" },
		eii{ ICON_VIHARA, "vihara", "Vihara" },
		eii{ ICON_VIRUS, "virus", "Virus" },
		eii{ ICON_VIRUS_COVID, "virus_covid", "Virus covid" },
		eii{ ICON_VIRUS_COVID_SLASH, "virus_covid_slash", "Virus covid slash" },
		eii{ ICON_VIRUS_SLASH, "virus_slash", "Virus slash" },
		eii{ ICON_VIRUSES, "viruses", "Viruses" },
		eii{ ICON_VOICEMAIL, "voicemail", "Voicemail" },
		eii{ ICON_VOLCANO, "volcano", "Volcano" },
		eii{ ICON_VOLLEYBALL, "volleyball", "Volleyball" },
		eii{ ICON_VOLUME_HIGH, "volume_high", "Volume high" },
		eii{ ICON_VOLUME_LOW, "volume_low", "Volume low" },
		eii{ ICON_VOLUME_OFF, "volume_off", "Volume off" },
		eii{ ICON_VOLUME_XMARK, "volume_xmark", "Volume xmark" },
		eii{ ICON_VR_CARDBOARD, "vr_cardboard", "Vr cardboard" },
		eii{ ICON_WALKIE_TALKIE, "walkie_talkie", "Walkie talkie" },
		eii{ ICON_WALLET, "wallet", "Wallet" },
		eii{ ICON_WAND_MAGIC, "wand_magic", "Wand magic" },
		eii{ ICON_WAND_MAGIC_SPARKLES, "wand_magic_sparkles", "Wand magic sparkles" },
		eii{ ICON_WAND_SPARKLES, "wand_sparkles", "Wand sparkles" },
		eii{ ICON_WAREHOUSE, "warehouse", "Warehouse" },
		eii{ ICON_WATER, "water", "Water" },
		eii{ ICON_WATER_LADDER, "water_ladder", "Water ladder" },
		eii{ ICON_WAVE_SQUARE, "wave_square", "Wave square" },
		eii{ ICON_WEIGHT_HANGING, "weight_hanging", "Weight hanging" },
		eii{ ICON_WEIGHT_SCALE, "weight_scale", "Weight scale" },
		eii{ ICON_WHEAT_AWN, "wheat_awn", "Wheat awn" },
		eii{ ICON_WHEAT_AWN_CIRCLE_EXCLAMATION, "wheat_awn_circle_exclamation", "Wheat awn circle exclamation" },
		eii{ ICON_WHEELCHAIR, "wheelchair", "Wheelchair" },
		eii{ ICON_WHEELCHAIR_MOVE, "wheelchair_move", "Wheelchair move" },
		eii{ ICON_WHISKEY_GLASS, "whiskey_glass", "Whiskey glass" },
		eii{ ICON_WIFI, "wifi", "Wifi" },
		eii{ ICON_WIND, "wind", "Wind" },
		eii{ ICON_WINDOW_MAXIMIZE, "window_maximize", "Window maximize" },
		eii{ ICON_WINDOW_MINIMIZE, "window_minimize", "Window minimize" },
		eii{ ICON_WINDOW_RESTORE, "window_restore", "Window restore" },
		eii{ ICON_WINE_BOTTLE, "wine_bottle", "Wine bottle" },
		eii{ ICON_WINE_GLASS, "wine_glass", "Wine glass" },
		eii{ ICON_WINE_GLASS_EMPTY, "wine_glass_empty", "Wine glass empty" },
		eii{ ICON_WON_SIGN, "won_sign", "Won sign" },
		eii{ ICON_WORM, "worm", "Worm" },
		eii{ ICON_WRENCH, "wrench", "Wrench" },
		eii{ ICON_X_RAY, "x_ray", "X ray" },
		eii{ ICON_XMARK, "xmark", "Xmark" },
		eii{ ICON_XMARKS_LINES, "xmarks_lines", "Xmarks lines" },
		eii{ ICON_YEN_SIGN, "yen_sign", "Yen sign" },
		eii{ ICON_YIN_YANG, "yin_yang", "Yin yang" },
	};
} // namespace fields_editor
